# Phase 13: Methodology-Clean JEPA Continuation Test

This local CUDA notebook answers the Phase 12 baseline concern directly.

Primary question: does JEPA continuation improve the released dSVA checkpoint compared with doing nothing, on the exact same broader victim panel?

Protocol:

- Evaluate the untouched released dSVA checkpoint on five victims: `resnet50`, `convnext_tiny`, `vit_b_16`, `efficientnet_b0`, `swin_t`.
- Run a JEPA-heavy continuation ablation from the released checkpoint: `jepa_weight` 0.2, 0.3, 0.5, 1.0 for 2 epochs.
- Keep matched DINO+MAE continuation controls as diagnostics, not as the main baseline.
- Train on 1000 Imagenette train images, evaluate on full Imagenette validation coverage via `eval_limit=5000`.
- Decide using gains vs untouched released dSVA first; matched continuation gains are secondary.

## Setup

In [1]:
import torch
print('CUDA available:', torch.cuda.is_available())
if torch.cuda.is_available():
    print('GPU:', torch.cuda.get_device_name(0))

assert torch.cuda.is_available(), 'A local CUDA GPU is required for this experiment.'

CUDA available: True
GPU: NVIDIA GeForce RTX 2060 SUPER

In [2]:
from pathlib import Path

cwd = Path.cwd()
candidates = [cwd, cwd.parent]
REPO_ROOT = next(
    (path for path in candidates if (path / 'scripts' / 'sweep_dsva_jepa_finetune.py').exists()),
    None,
)
assert REPO_ROOT is not None, f'Could not find repo root from {cwd}'
print('Repo root:', REPO_ROOT)

Repo root: d:\Florent\Desktop\jepa-transfer-attacks

In [3]:
TRAIN_ROOT = REPO_ROOT / 'imagenette2-320' / 'train'
VAL_ROOT = REPO_ROOT / 'imagenette2-320' / 'val'
DSVA_CHECKPOINT = REPO_ROOT / 'external' / 'models' / 'dSVA' / 'model.pth'

assert TRAIN_ROOT.exists(), f'Missing training data: {TRAIN_ROOT}'
assert VAL_ROOT.exists(), f'Missing validation data: {VAL_ROOT}'
assert DSVA_CHECKPOINT.exists(), f'Missing dSVA checkpoint: {DSVA_CHECKPOINT}'

print('Train root:', TRAIN_ROOT)
print('Val root:', VAL_ROOT)
print('dSVA checkpoint:', DSVA_CHECKPOINT)

Train root: d:\Florent\Desktop\jepa-transfer-attacks\imagenette2-320\train
Val root: d:\Florent\Desktop\jepa-transfer-attacks\imagenette2-320\val
dSVA checkpoint: d:\Florent\Desktop\jepa-transfer-attacks\external\models\dSVA\model.pth

## Configuration

In [4]:
SEEDS = [0, 1, 2]
TRAIN_LIMIT = 1000
EVAL_LIMIT = 5000
EPSILON = '0.06274509803921569'
LR = '0.00005'
EPOCHS = 2
OUTPUT_MODE = 'scaled-delta'
VICTIMS = ['resnet50', 'convnext_tiny', 'vit_b_16', 'efficientnet_b0', 'swin_t']
JEPA_CONFIGS = ['0.2:0.00005', '0.3:0.00005', '0.5:0.00005', '1.0:0.00005']

PHASE13_OUTPUT_DIR = REPO_ROOT / 'results' / 'phase13_jepa_weight_ablation'
PHASE13_ANALYSIS_DIR = REPO_ROOT / 'results' / 'phase13_analysis'
PHASE13_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
PHASE13_ANALYSIS_DIR.mkdir(parents=True, exist_ok=True)

TRAIN_PERF_FLAGS = ['--compile', '--compile-mode', 'reduce-overhead']
EVAL_PERF_FLAGS = ['--eval-amp', *TRAIN_PERF_FLAGS]

print('Output dir:', PHASE13_OUTPUT_DIR)
print('Analysis dir:', PHASE13_ANALYSIS_DIR)
print('Victims:', VICTIMS)
print('JEPA configs:', JEPA_CONFIGS)
print('Performance flags:', EVAL_PERF_FLAGS)

Output dir: d:\Florent\Desktop\jepa-transfer-attacks\results\phase13_jepa_weight_ablation
Analysis dir: d:\Florent\Desktop\jepa-transfer-attacks\results\phase13_analysis
Victims: ['resnet50', 'convnext_tiny', 'vit_b_16', 'efficientnet_b0', 'swin_t']
JEPA configs: ['0.2:0.00005', '0.3:0.00005', '0.5:0.00005', '1.0:0.00005']
Performance flags: ['--eval-amp', '--compile', '--compile-mode', 'reduce-overhead']

## Helpers

In [5]:
import subprocess, sys
from pathlib import Path

def run_checked(cmd):
    print('\n' + ' '.join(map(str, cmd)), flush=True)
    log_dir = REPO_ROOT / 'results' / 'phase13_logs'
    log_dir.mkdir(parents=True, exist_ok=True)
    log_path = log_dir / (Path(str(cmd[1])).stem + '_' + str(len(list(log_dir.glob('*.log')))) + '.log')
    with log_path.open('w', encoding='utf-8', errors='replace') as handle:
        result = subprocess.run(
            cmd,
            cwd=REPO_ROOT,
            text=True,
            stdout=handle,
            stderr=subprocess.STDOUT,
        )
    text = log_path.read_text(encoding='utf-8', errors='replace')
    print(text[-12000:])
    print('Log:', log_path)
    if result.returncode != 0:
        raise RuntimeError(f"Command failed with exit code {result.returncode}: {' '.join(map(str, cmd))}")
    return result

## Smoke Test

In [6]:
smoke_csv = REPO_ROOT / 'results' / 'phase13_smoke_released_dsva_broader.csv'
if smoke_csv.exists():
    print('Skipping existing smoke CSV:', smoke_csv)
else:
    run_checked([
        sys.executable,
        'scripts/run_dsva_checkpoint_attack.py',
        '--data-root', str(VAL_ROOT),
        '--checkpoint', str(DSVA_CHECKPOINT),
        '--output-mode', 'adv',
        '--limit', '16',
        '--batch-size', '8',
        '--epsilon', EPSILON,
        '--victims', *VICTIMS,
        '--device', 'cuda',
        '--output-csv', str(smoke_csv),
        '--amp',
    ])

c:\Users\Florent\anaconda3\python.exe scripts/run_dsva_checkpoint_attack.py --data-root d:\Florent\Desktop\jepa-transfer-attacks\imagenette2-320\val --checkpoint d:\Florent\Desktop\jepa-transfer-attacks\external\models\dSVA\model.pth --output-mode adv --limit 16 --batch-size 8 --epsilon 0.06274509803921569 --victims resnet50 convnext_tiny vit_b_16 efficientnet_b0 swin_t --device cuda --output-csv d:\Florent\Desktop\jepa-transfer-attacks\results\phase13_smoke_released_dsva_broader.csv --amp

dSVA checkpoint transfer:   0%|          | 0/2 [00:00<?, ?it/s]
dSVA checkpoint transfer:  50%|█████     | 1/2 [00:11<00:11, 11.09s/it]
dSVA checkpoint transfer: 100%|██████████| 2/2 [00:11<00:00,  4.72s/it]
dSVA checkpoint transfer: 100%|██████████| 2/2 [00:11<00:00,  5.68s/it]
| model | n | clean_acc | adv_acc | acc_drop | attack_success_rate |
| --- | ---: | ---: | ---: | ---: | ---: |
| resnet50 | 16 | 93.75% | 37.50% | 56.25% | 60.00% |
| convnext_tiny | 16 | 93.75% | 43.75% | 50.00% | 53.33% |
| vit_b_16 | 16 | 100.00% | 6.25% | 93.75% | 93.75% |
| efficientnet_b0 | 16 | 93.75% | 12.50% | 81.25% | 86.67% |
| swin_t | 16 | 93.75% | 50.00% | 43.75% | 46.67% |

Mean transfer success: 68.08%
Max L_inf delta: 0.062745
Saved metrics to d:\Florent\Desktop\jepa-transfer-attacks\results\phase13_smoke_released_dsva_broader.csv

Log: d:\Florent\Desktop\jepa-transfer-attacks\results\phase13_logs\run_dsva_checkpoint_attack_0.log

## Untouched Released dSVA Broader Baseline

In [7]:
untouched_csv = PHASE13_ANALYSIS_DIR / 'official_dsva_broader_eval.csv'
if untouched_csv.exists():
    print('Skipping existing untouched baseline:', untouched_csv)
else:
    run_checked([
        sys.executable,
        'scripts/run_dsva_checkpoint_attack.py',
        '--data-root', str(VAL_ROOT),
        '--checkpoint', str(DSVA_CHECKPOINT),
        '--output-mode', 'adv',
        '--limit', str(EVAL_LIMIT),
        '--batch-size', '8',
        '--epsilon', EPSILON,
        '--victims', *VICTIMS,
        '--device', 'cuda',
        '--output-csv', str(untouched_csv),
        '--amp',
    ])

c:\Users\Florent\anaconda3\python.exe scripts/run_dsva_checkpoint_attack.py --data-root d:\Florent\Desktop\jepa-transfer-attacks\imagenette2-320\val --checkpoint d:\Florent\Desktop\jepa-transfer-attacks\external\models\dSVA\model.pth --output-mode adv --limit 5000 --batch-size 8 --epsilon 0.06274509803921569 --victims resnet50 convnext_tiny vit_b_16 efficientnet_b0 swin_t --device cuda --output-csv d:\Florent\Desktop\jepa-transfer-attacks\results\phase13_analysis\official_dsva_broader_eval.csv --amp
91 [01:47<00:38,  3.90it/s]
dSVA checkpoint transfer:  70%|██████▉   | 343/491 [01:47<00:37,  3.93it/s]
dSVA checkpoint transfer:  70%|███████   | 344/491 [01:48<00:37,  3.88it/s]
dSVA checkpoint transfer:  70%|███████   | 345/491 [01:48<00:37,  3.92it/s]
dSVA checkpoint transfer:  70%|███████   | 346/491 [01:48<00:36,  3.98it/s]
dSVA checkpoint transfer:  71%|███████   | 347/491 [01:48<00:36,  3.95it/s]
dSVA checkpoint transfer:  71%|███████   | 348/491 [01:49<00:36,  3.93it/s]
dSVA checkpoint transfer:  71%|███████   | 349/491 [01:49<00:37,  3.82it/s]
dSVA checkpoint transfer:  71%|███████▏  | 350/491 [01:49<00:38,  3.70it/s]
dSVA checkpoint transfer:  71%|███████▏  | 351/491 [01:50<00:37,  3.71it/s]
dSVA checkpoint transfer:  72%|███████▏  | 352/491 [01:50<00:39,  3.53it/s]
dSVA checkpoint transfer:  72%|███████▏  | 353/491 [01:50<00:39,  3.50it/s]
dSVA checkpoint transfer:  72%|███████▏  | 354/491 [01:50<00:37,  3.65it/s]
dSVA checkpoint transfer:  72%|███████▏  | 355/491 [01:51<00:36,  3.74it/s]
dSVA checkpoint transfer:  73%|███████▎  | 356/491 [01:51<00:38,  3.46it/s]
dSVA checkpoint transfer:  73%|███████▎  | 357/491 [01:51<00:38,  3.44it/s]
dSVA checkpoint transfer:  73%|███████▎  | 358/491 [01:52<00:38,  3.47it/s]
dSVA checkpoint transfer:  73%|███████▎  | 359/491 [01:52<00:36,  3.63it/s]
dSVA checkpoint transfer:  73%|███████▎  | 360/491 [01:52<00:35,  3.70it/s]
dSVA checkpoint transfer:  74%|███████▎  | 361/491 [01:52<00:34,  3.76it/s]
dSVA checkpoint transfer:  74%|███████▎  | 362/491 [01:53<00:34,  3.75it/s]
dSVA checkpoint transfer:  74%|███████▍  | 363/491 [01:53<00:34,  3.72it/s]
dSVA checkpoint transfer:  74%|███████▍  | 364/491 [01:53<00:34,  3.64it/s]
dSVA checkpoint transfer:  74%|███████▍  | 365/491 [01:53<00:35,  3.56it/s]
dSVA checkpoint transfer:  75%|███████▍  | 366/491 [01:54<00:34,  3.60it/s]
dSVA checkpoint transfer:  75%|███████▍  | 367/491 [01:54<00:33,  3.66it/s]
dSVA checkpoint transfer:  75%|███████▍  | 368/491 [01:54<00:32,  3.75it/s]
dSVA checkpoint transfer:  75%|███████▌  | 369/491 [01:54<00:32,  3.79it/s]
dSVA checkpoint transfer:  75%|███████▌  | 370/491 [01:55<00:31,  3.84it/s]
dSVA checkpoint transfer:  76%|███████▌  | 371/491 [01:55<00:33,  3.58it/s]
dSVA checkpoint transfer:  76%|███████▌  | 372/491 [01:55<00:33,  3.53it/s]
dSVA checkpoint transfer:  76%|███████▌  | 373/491 [01:56<00:32,  3.63it/s]
dSVA checkpoint transfer:  76%|███████▌  | 374/491 [01:56<00:31,  3.68it/s]
dSVA checkpoint transfer:  76%|███████▋  | 375/491 [01:56<00:31,  3.65it/s]
dSVA checkpoint transfer:  77%|███████▋  | 376/491 [01:56<00:32,  3.57it/s]
dSVA checkpoint transfer:  77%|███████▋  | 377/491 [01:57<00:32,  3.48it/s]
dSVA checkpoint transfer:  77%|███████▋  | 378/491 [01:57<00:31,  3.63it/s]
dSVA checkpoint transfer:  77%|███████▋  | 379/491 [01:57<00:29,  3.73it/s]
dSVA checkpoint transfer:  77%|███████▋  | 380/491 [01:58<00:29,  3.81it/s]
dSVA checkpoint transfer:  78%|███████▊  | 381/491 [01:58<00:28,  3.90it/s]
dSVA checkpoint transfer:  78%|███████▊  | 382/491 [01:58<00:27,  3.91it/s]
dSVA checkpoint transfer:  78%|███████▊  | 383/491 [01:58<00:27,  3.95it/s]
dSVA checkpoint transfer:  78%|███████▊  | 384/491 [01:58<00:26,  4.00it/s]
dSVA checkpoint transfer:  78%|███████▊  | 385/491 [01:59<00:26,  4.02it/s]
dSVA checkpoint transfer:  79%|███████▊  | 386/491 [01:59<00:26,  4.03it/s]
dSVA checkpoint transfer:  79%|███████▉  | 387/491 [01:59<00:25,  4.05it/s]
dSVA checkpoint transfer:  79%|███████▉  | 388/491 [01:59<00:25,  4.03it/s]
dSVA checkpoint transfer:  79%|███████▉  | 389/491 [02:00<00:26,  3.80it/s]
dSVA checkpoint transfer:  79%|███████▉  | 390/491 [02:00<00:26,  3.80it/s]
dSVA checkpoint transfer:  80%|███████▉  | 391/491 [02:00<00:26,  3.78it/s]
dSVA checkpoint transfer:  80%|███████▉  | 392/491 [02:01<00:25,  3.86it/s]
dSVA checkpoint transfer:  80%|████████  | 393/491 [02:01<00:25,  3.90it/s]
dSVA checkpoint transfer:  80%|████████  | 394/491 [02:01<00:24,  3.90it/s]
dSVA checkpoint transfer:  80%|████████  | 395/491 [02:01<00:24,  3.92it/s]
dSVA checkpoint transfer:  81%|████████  | 396/491 [02:02<00:24,  3.93it/s]
dSVA checkpoint transfer:  81%|████████  | 397/491 [02:02<00:23,  3.97it/s]
dSVA checkpoint transfer:  81%|████████  | 398/491 [02:02<00:23,  3.96it/s]
dSVA checkpoint transfer:  81%|████████▏ | 399/491 [02:02<00:23,  3.98it/s]
dSVA checkpoint transfer:  81%|████████▏ | 400/491 [02:03<00:22,  3.96it/s]
dSVA checkpoint transfer:  82%|████████▏ | 401/491 [02:03<00:22,  3.98it/s]
dSVA checkpoint transfer:  82%|████████▏ | 402/491 [02:03<00:22,  3.98it/s]
dSVA checkpoint transfer:  82%|████████▏ | 403/491 [02:03<00:22,  3.96it/s]
dSVA checkpoint transfer:  82%|████████▏ | 404/491 [02:04<00:22,  3.93it/s]
dSVA checkpoint transfer:  82%|████████▏ | 405/491 [02:04<00:22,  3.88it/s]
dSVA checkpoint transfer:  83%|████████▎ | 406/491 [02:04<00:21,  3.91it/s]
dSVA checkpoint transfer:  83%|████████▎ | 407/491 [02:04<00:21,  3.99it/s]
dSVA checkpoint transfer:  83%|████████▎ | 408/491 [02:05<00:21,  3.92it/s]
dSVA checkpoint transfer:  83%|████████▎ | 409/491 [02:05<00:21,  3.88it/s]
dSVA checkpoint transfer:  84%|████████▎ | 410/491 [02:05<00:20,  3.87it/s]
dSVA checkpoint transfer:  84%|████████▎ | 411/491 [02:05<00:20,  3.92it/s]
dSVA checkpoint transfer:  84%|████████▍ | 412/491 [02:06<00:20,  3.94it/s]
dSVA checkpoint transfer:  84%|████████▍ | 413/491 [02:06<00:19,  4.00it/s]
dSVA checkpoint transfer:  84%|████████▍ | 414/491 [02:06<00:19,  4.04it/s]
dSVA checkpoint transfer:  85%|████████▍ | 415/491 [02:06<00:19,  3.98it/s]
dSVA checkpoint transfer:  85%|████████▍ | 416/491 [02:07<00:18,  4.00it/s]
dSVA checkpoint transfer:  85%|████████▍ | 417/491 [02:07<00:18,  3.95it/s]
dSVA checkpoint transfer:  85%|████████▌ | 418/491 [02:07<00:18,  4.01it/s]
dSVA checkpoint transfer:  85%|████████▌ | 419/491 [02:07<00:17,  4.01it/s]
dSVA checkpoint transfer:  86%|████████▌ | 420/491 [02:08<00:17,  4.04it/s]
dSVA checkpoint transfer:  86%|████████▌ | 421/491 [02:08<00:17,  4.06it/s]
dSVA checkpoint transfer:  86%|████████▌ | 422/491 [02:08<00:17,  4.03it/s]
dSVA checkpoint transfer:  86%|████████▌ | 423/491 [02:08<00:17,  3.98it/s]
dSVA checkpoint transfer:  86%|████████▋ | 424/491 [02:09<00:16,  3.99it/s]
dSVA checkpoint transfer:  87%|████████▋ | 425/491 [02:09<00:16,  3.98it/s]
dSVA checkpoint transfer:  87%|████████▋ | 426/491 [02:09<00:16,  3.93it/s]
dSVA checkpoint transfer:  87%|████████▋ | 427/491 [02:09<00:17,  3.66it/s]
dSVA checkpoint transfer:  87%|████████▋ | 428/491 [02:10<00:17,  3.65it/s]
dSVA checkpoint transfer:  87%|████████▋ | 429/491 [02:10<00:16,  3.67it/s]
dSVA checkpoint transfer:  88%|████████▊ | 430/491 [02:10<00:17,  3.58it/s]
dSVA checkpoint transfer:  88%|████████▊ | 431/491 [02:11<00:16,  3.72it/s]
dSVA checkpoint transfer:  88%|████████▊ | 432/491 [02:11<00:16,  3.66it/s]
dSVA checkpoint transfer:  88%|████████▊ | 433/491 [02:11<00:16,  3.50it/s]
dSVA checkpoint transfer:  88%|████████▊ | 434/491 [02:11<00:16,  3.55it/s]
dSVA checkpoint transfer:  89%|████████▊ | 435/491 [02:12<00:15,  3.66it/s]
dSVA checkpoint transfer:  89%|████████▉ | 436/491 [02:12<00:17,  3.17it/s]
dSVA checkpoint transfer:  89%|████████▉ | 437/491 [02:12<00:18,  2.98it/s]
dSVA checkpoint transfer:  89%|████████▉ | 438/491 [02:13<00:17,  3.02it/s]
dSVA checkpoint transfer:  89%|████████▉ | 439/491 [02:13<00:16,  3.07it/s]
dSVA checkpoint transfer:  90%|████████▉ | 440/491 [02:13<00:16,  3.12it/s]
dSVA checkpoint transfer:  90%|████████▉ | 441/491 [02:14<00:15,  3.14it/s]
dSVA checkpoint transfer:  90%|█████████ | 442/491 [02:14<00:15,  3.16it/s]
dSVA checkpoint transfer:  90%|█████████ | 443/491 [02:14<00:15,  3.19it/s]
dSVA checkpoint transfer:  90%|█████████ | 444/491 [02:15<00:14,  3.18it/s]
dSVA checkpoint transfer:  91%|█████████ | 445/491 [02:15<00:14,  3.20it/s]
dSVA checkpoint transfer:  91%|█████████ | 446/491 [02:15<00:14,  3.19it/s]
dSVA checkpoint transfer:  91%|█████████ | 447/491 [02:16<00:13,  3.19it/s]
dSVA checkpoint transfer:  91%|█████████ | 448/491 [02:16<00:13,  3.20it/s]
dSVA checkpoint transfer:  91%|█████████▏| 449/491 [02:16<00:13,  3.16it/s]
dSVA checkpoint transfer:  92%|█████████▏| 450/491 [02:17<00:12,  3.16it/s]
dSVA checkpoint transfer:  92%|█████████▏| 451/491 [02:17<00:12,  3.21it/s]
dSVA checkpoint transfer:  92%|█████████▏| 452/491 [02:17<00:12,  3.16it/s]
dSVA checkpoint transfer:  92%|█████████▏| 453/491 [02:17<00:11,  3.18it/s]
dSVA checkpoint transfer:  92%|█████████▏| 454/491 [02:18<00:11,  3.20it/s]
dSVA checkpoint transfer:  93%|█████████▎| 455/491 [02:18<00:11,  3.20it/s]
dSVA checkpoint transfer:  93%|█████████▎| 456/491 [02:18<00:10,  3.20it/s]
dSVA checkpoint transfer:  93%|█████████▎| 457/491 [02:19<00:10,  3.23it/s]
dSVA checkpoint transfer:  93%|█████████▎| 458/491 [02:19<00:10,  3.22it/s]
dSVA checkpoint transfer:  93%|█████████▎| 459/491 [02:19<00:09,  3.23it/s]
dSVA checkpoint transfer:  94%|█████████▎| 460/491 [02:20<00:09,  3.23it/s]
dSVA checkpoint transfer:  94%|█████████▍| 461/491 [02:20<00:10,  2.95it/s]
dSVA checkpoint transfer:  94%|█████████▍| 462/491 [02:20<00:09,  2.93it/s]
dSVA checkpoint transfer:  94%|█████████▍| 463/491 [02:21<00:09,  2.93it/s]
dSVA checkpoint transfer:  95%|█████████▍| 464/491 [02:21<00:08,  3.01it/s]
dSVA checkpoint transfer:  95%|█████████▍| 465/491 [02:21<00:08,  3.09it/s]
dSVA checkpoint transfer:  95%|█████████▍| 466/491 [02:22<00:07,  3.13it/s]
dSVA checkpoint transfer:  95%|█████████▌| 467/491 [02:22<00:07,  3.15it/s]
dSVA checkpoint transfer:  95%|█████████▌| 468/491 [02:22<00:07,  3.19it/s]
dSVA checkpoint transfer:  96%|█████████▌| 469/491 [02:23<00:06,  3.21it/s]
dSVA checkpoint transfer:  96%|█████████▌| 470/491 [02:23<00:06,  3.22it/s]
dSVA checkpoint transfer:  96%|█████████▌| 471/491 [02:23<00:06,  3.20it/s]
dSVA checkpoint transfer:  96%|█████████▌| 472/491 [02:24<00:05,  3.21it/s]
dSVA checkpoint transfer:  96%|█████████▋| 473/491 [02:24<00:05,  3.23it/s]
dSVA checkpoint transfer:  97%|█████████▋| 474/491 [02:24<00:05,  3.22it/s]
dSVA checkpoint transfer:  97%|█████████▋| 475/491 [02:24<00:04,  3.24it/s]
dSVA checkpoint transfer:  97%|█████████▋| 476/491 [02:25<00:04,  3.25it/s]
dSVA checkpoint transfer:  97%|█████████▋| 477/491 [02:25<00:04,  3.23it/s]
dSVA checkpoint transfer:  97%|█████████▋| 478/491 [02:25<00:04,  3.14it/s]
dSVA checkpoint transfer:  98%|█████████▊| 479/491 [02:26<00:03,  3.12it/s]
dSVA checkpoint transfer:  98%|█████████▊| 480/491 [02:26<00:03,  3.02it/s]
dSVA checkpoint transfer:  98%|█████████▊| 481/491 [02:26<00:03,  3.04it/s]
dSVA checkpoint transfer:  98%|█████████▊| 482/491 [02:27<00:02,  3.10it/s]
dSVA checkpoint transfer:  98%|█████████▊| 483/491 [02:27<00:02,  3.13it/s]
dSVA checkpoint transfer:  99%|█████████▊| 484/491 [02:27<00:02,  3.15it/s]
dSVA checkpoint transfer:  99%|█████████▉| 485/491 [02:28<00:01,  3.15it/s]
dSVA checkpoint transfer:  99%|█████████▉| 486/491 [02:28<00:01,  3.15it/s]
dSVA checkpoint transfer:  99%|█████████▉| 487/491 [02:28<00:01,  3.17it/s]
dSVA checkpoint transfer:  99%|█████████▉| 488/491 [02:29<00:00,  3.17it/s]
dSVA checkpoint transfer: 100%|█████████▉| 489/491 [02:29<00:00,  3.18it/s]
dSVA checkpoint transfer: 100%|█████████▉| 490/491 [02:29<00:00,  3.19it/s]
dSVA checkpoint transfer: 100%|██████████| 491/491 [02:38<00:00,  2.87s/it]
dSVA checkpoint transfer: 100%|██████████| 491/491 [02:38<00:00,  3.10it/s]
| model | n | clean_acc | adv_acc | acc_drop | attack_success_rate |
| --- | ---: | ---: | ---: | ---: | ---: |
| resnet50 | 3925 | 87.34% | 27.92% | 59.41% | 68.90% |
| convnext_tiny | 3925 | 87.59% | 40.03% | 47.57% | 55.44% |
| vit_b_16 | 3925 | 91.85% | 21.12% | 70.73% | 77.36% |
| efficientnet_b0 | 3925 | 86.04% | 4.82% | 81.22% | 94.61% |
| swin_t | 3925 | 84.66% | 42.88% | 41.78% | 50.89% |

Mean transfer success: 69.44%
Max L_inf delta: 0.062745
Saved metrics to d:\Florent\Desktop\jepa-transfer-attacks\results\phase13_analysis\official_dsva_broader_eval.csv

Log: d:\Florent\Desktop\jepa-transfer-attacks\results\phase13_logs\run_dsva_checkpoint_attack_1.log

In [8]:
import pandas as pd

untouched = pd.read_csv(untouched_csv)
untouched_mean = untouched['attack_success_rate'].mean()
print('Untouched broader mean:', f'{100 * untouched_mean:.2f}%')
untouched

Untouched broader mean: 69.44%

             model     n  clean_acc   adv_acc  acc_drop  attack_success_rate
0         resnet50  3925   0.873376  0.279236  0.594140             0.689032
1    convnext_tiny  3925   0.875924  0.400255  0.475669             0.554392
2         vit_b_16  3925   0.918471  0.211210  0.707261             0.773648
3  efficientnet_b0  3925   0.860382  0.048153  0.812229             0.946106
4           swin_t  3925   0.846624  0.428790  0.417834             0.508878

## JEPA-Heavy Weight Ablation

In [9]:
for seed in SEEDS:
    seed_dir = PHASE13_OUTPUT_DIR / f'seed_{seed}'
    seed_dir.mkdir(parents=True, exist_ok=True)
    cmd = [
        sys.executable,
        'scripts/sweep_dsva_jepa_finetune.py',
        '--train-root', str(TRAIN_ROOT),
        '--val-root', str(VAL_ROOT),
        '--init-checkpoint', str(DSVA_CHECKPOINT),
        '--output-dir', str(seed_dir),
        '--run-prefix', f'phase13_seed{seed}_jepa_heavy_ep{EPOCHS}',
        '--configs', *JEPA_CONFIGS,
        '--limit', str(TRAIN_LIMIT),
        '--eval-limit', str(EVAL_LIMIT),
        '--epochs', str(EPOCHS),
        '--batch-size', '1',
        '--eval-batch-size', '8',
        '--grad-accum-steps', '8',
        '--epsilon', EPSILON,
        '--output-mode', OUTPUT_MODE,
        '--victims', *VICTIMS,
        '--device', 'cuda',
        '--seed', str(seed),
        '--normalize-loss-weights',
        '--skip-existing',
        *EVAL_PERF_FLAGS,
    ]
    run_checked(cmd)

c:\Users\Florent\anaconda3\python.exe scripts/sweep_dsva_jepa_finetune.py --train-root d:\Florent\Desktop\jepa-transfer-attacks\imagenette2-320\train --val-root d:\Florent\Desktop\jepa-transfer-attacks\imagenette2-320\val --init-checkpoint d:\Florent\Desktop\jepa-transfer-attacks\external\models\dSVA\model.pth --output-dir d:\Florent\Desktop\jepa-transfer-attacks\results\phase13_jepa_weight_ablation\seed_0 --run-prefix phase13_seed0_jepa_heavy_ep2 --configs 0.2:0.00005 0.3:0.00005 0.5:0.00005 1.0:0.00005 --limit 1000 --eval-limit 5000 --epochs 2 --batch-size 1 --eval-batch-size 8 --grad-accum-steps 8 --epsilon 0.06274509803921569 --output-mode scaled-delta --victims resnet50 convnext_tiny vit_b_16 efficientnet_b0 swin_t --device cuda --seed 0 --normalize-loss-weights --skip-existing --eval-amp --compile --compile-mode reduce-overhead
eckpoint transfer:  71%|███████   | 347/491 [01:55<00:50,  2.85it/s]
dSVA checkpoint transfer:  71%|███████   | 348/491 [01:55<00:50,  2.86it/s]
dSVA checkpoint transfer:  71%|███████   | 349/491 [01:55<00:49,  2.86it/s]
dSVA checkpoint transfer:  71%|███████▏  | 350/491 [01:56<00:49,  2.82it/s]
dSVA checkpoint transfer:  71%|███████▏  | 351/491 [01:56<00:49,  2.83it/s]
dSVA checkpoint transfer:  72%|███████▏  | 352/491 [01:56<00:48,  2.88it/s]
dSVA checkpoint transfer:  72%|███████▏  | 353/491 [01:57<00:44,  3.10it/s]
dSVA checkpoint transfer:  72%|███████▏  | 354/491 [01:57<00:41,  3.28it/s]
dSVA checkpoint transfer:  72%|███████▏  | 355/491 [01:57<00:39,  3.47it/s]
dSVA checkpoint transfer:  73%|███████▎  | 356/491 [01:57<00:37,  3.61it/s]
dSVA checkpoint transfer:  73%|███████▎  | 357/491 [01:58<00:36,  3.71it/s]
dSVA checkpoint transfer:  73%|███████▎  | 358/491 [01:58<00:38,  3.46it/s]
dSVA checkpoint transfer:  73%|███████▎  | 359/491 [01:58<00:40,  3.29it/s]
dSVA checkpoint transfer:  73%|███████▎  | 360/491 [01:59<00:41,  3.13it/s]
dSVA checkpoint transfer:  74%|███████▎  | 361/491 [01:59<00:42,  3.08it/s]
dSVA checkpoint transfer:  74%|███████▎  | 362/491 [01:59<00:42,  3.01it/s]
dSVA checkpoint transfer:  74%|███████▍  | 363/491 [02:00<00:40,  3.17it/s]
dSVA checkpoint transfer:  74%|███████▍  | 364/491 [02:00<00:37,  3.39it/s]
dSVA checkpoint transfer:  74%|███████▍  | 365/491 [02:00<00:35,  3.56it/s]
dSVA checkpoint transfer:  75%|███████▍  | 366/491 [02:00<00:33,  3.72it/s]
dSVA checkpoint transfer:  75%|███████▍  | 367/491 [02:01<00:32,  3.77it/s]
dSVA checkpoint transfer:  75%|███████▍  | 368/491 [02:01<00:31,  3.85it/s]
dSVA checkpoint transfer:  75%|███████▌  | 369/491 [02:01<00:31,  3.87it/s]
dSVA checkpoint transfer:  75%|███████▌  | 370/491 [02:01<00:30,  3.95it/s]
dSVA checkpoint transfer:  76%|███████▌  | 371/491 [02:02<00:30,  3.97it/s]
dSVA checkpoint transfer:  76%|███████▌  | 372/491 [02:02<00:30,  3.96it/s]
dSVA checkpoint transfer:  76%|███████▌  | 373/491 [02:02<00:29,  4.00it/s]
dSVA checkpoint transfer:  76%|███████▌  | 374/491 [02:02<00:29,  3.99it/s]
dSVA checkpoint transfer:  76%|███████▋  | 375/491 [02:03<00:28,  4.05it/s]
dSVA checkpoint transfer:  77%|███████▋  | 376/491 [02:03<00:28,  4.05it/s]
dSVA checkpoint transfer:  77%|███████▋  | 377/491 [02:03<00:28,  4.04it/s]
dSVA checkpoint transfer:  77%|███████▋  | 378/491 [02:03<00:28,  4.00it/s]
dSVA checkpoint transfer:  77%|███████▋  | 379/491 [02:03<00:27,  4.03it/s]
dSVA checkpoint transfer:  77%|███████▋  | 380/491 [02:04<00:27,  3.98it/s]
dSVA checkpoint transfer:  78%|███████▊  | 381/491 [02:04<00:27,  4.03it/s]
dSVA checkpoint transfer:  78%|███████▊  | 382/491 [02:04<00:26,  4.07it/s]
dSVA checkpoint transfer:  78%|███████▊  | 383/491 [02:04<00:26,  4.07it/s]
dSVA checkpoint transfer:  78%|███████▊  | 384/491 [02:05<00:26,  4.10it/s]
dSVA checkpoint transfer:  78%|███████▊  | 385/491 [02:05<00:25,  4.14it/s]
dSVA checkpoint transfer:  79%|███████▊  | 386/491 [02:05<00:25,  4.10it/s]
dSVA checkpoint transfer:  79%|███████▉  | 387/491 [02:05<00:25,  4.10it/s]
dSVA checkpoint transfer:  79%|███████▉  | 388/491 [02:06<00:25,  4.11it/s]
dSVA checkpoint transfer:  79%|███████▉  | 389/491 [02:06<00:24,  4.10it/s]
dSVA checkpoint transfer:  79%|███████▉  | 390/491 [02:06<00:24,  4.09it/s]
dSVA checkpoint transfer:  80%|███████▉  | 391/491 [02:06<00:24,  4.09it/s]
dSVA checkpoint transfer:  80%|███████▉  | 392/491 [02:07<00:24,  4.08it/s]
dSVA checkpoint transfer:  80%|████████  | 393/491 [02:07<00:24,  4.08it/s]
dSVA checkpoint transfer:  80%|████████  | 394/491 [02:07<00:23,  4.06it/s]
dSVA checkpoint transfer:  80%|████████  | 395/491 [02:07<00:23,  4.03it/s]
dSVA checkpoint transfer:  81%|████████  | 396/491 [02:08<00:23,  4.00it/s]
dSVA checkpoint transfer:  81%|████████  | 397/491 [02:08<00:23,  4.04it/s]
dSVA checkpoint transfer:  81%|████████  | 398/491 [02:08<00:23,  3.92it/s]
dSVA checkpoint transfer:  81%|████████▏ | 399/491 [02:08<00:23,  3.97it/s]
dSVA checkpoint transfer:  81%|████████▏ | 400/491 [02:09<00:22,  3.99it/s]
dSVA checkpoint transfer:  82%|████████▏ | 401/491 [02:09<00:22,  3.98it/s]
dSVA checkpoint transfer:  82%|████████▏ | 402/491 [02:09<00:22,  4.01it/s]
dSVA checkpoint transfer:  82%|████████▏ | 403/491 [02:09<00:22,  3.91it/s]
dSVA checkpoint transfer:  82%|████████▏ | 404/491 [02:10<00:22,  3.95it/s]
dSVA checkpoint transfer:  82%|████████▏ | 405/491 [02:10<00:22,  3.89it/s]
dSVA checkpoint transfer:  83%|████████▎ | 406/491 [02:10<00:21,  3.95it/s]
dSVA checkpoint transfer:  83%|████████▎ | 407/491 [02:10<00:21,  3.96it/s]
dSVA checkpoint transfer:  83%|████████▎ | 408/491 [02:11<00:20,  3.97it/s]
dSVA checkpoint transfer:  83%|████████▎ | 409/491 [02:11<00:20,  4.03it/s]
dSVA checkpoint transfer:  84%|████████▎ | 410/491 [02:11<00:20,  3.94it/s]
dSVA checkpoint transfer:  84%|████████▎ | 411/491 [02:11<00:20,  3.96it/s]
dSVA checkpoint transfer:  84%|████████▍ | 412/491 [02:12<00:19,  3.98it/s]
dSVA checkpoint transfer:  84%|████████▍ | 413/491 [02:12<00:19,  4.00it/s]
dSVA checkpoint transfer:  84%|████████▍ | 414/491 [02:12<00:19,  4.01it/s]
dSVA checkpoint transfer:  85%|████████▍ | 415/491 [02:12<00:19,  4.00it/s]
dSVA checkpoint transfer:  85%|████████▍ | 416/491 [02:13<00:18,  4.01it/s]
dSVA checkpoint transfer:  85%|████████▍ | 417/491 [02:13<00:20,  3.68it/s]
dSVA checkpoint transfer:  85%|████████▌ | 418/491 [02:13<00:21,  3.44it/s]
dSVA checkpoint transfer:  85%|████████▌ | 419/491 [02:14<00:22,  3.26it/s]
dSVA checkpoint transfer:  86%|████████▌ | 420/491 [02:14<00:22,  3.11it/s]
dSVA checkpoint transfer:  86%|████████▌ | 421/491 [02:14<00:23,  2.99it/s]
dSVA checkpoint transfer:  86%|████████▌ | 422/491 [02:15<00:23,  2.96it/s]
dSVA checkpoint transfer:  86%|████████▌ | 423/491 [02:15<00:22,  2.97it/s]
dSVA checkpoint transfer:  86%|████████▋ | 424/491 [02:15<00:22,  3.03it/s]
dSVA checkpoint transfer:  87%|████████▋ | 425/491 [02:16<00:21,  3.03it/s]
dSVA checkpoint transfer:  87%|████████▋ | 426/491 [02:16<00:21,  3.01it/s]
dSVA checkpoint transfer:  87%|████████▋ | 427/491 [02:16<00:21,  2.96it/s]
dSVA checkpoint transfer:  87%|████████▋ | 428/491 [02:17<00:21,  2.92it/s]
dSVA checkpoint transfer:  87%|████████▋ | 429/491 [02:17<00:21,  2.94it/s]
dSVA checkpoint transfer:  88%|████████▊ | 430/491 [02:17<00:20,  2.92it/s]
dSVA checkpoint transfer:  88%|████████▊ | 431/491 [02:18<00:20,  2.91it/s]
dSVA checkpoint transfer:  88%|████████▊ | 432/491 [02:18<00:19,  2.97it/s]
dSVA checkpoint transfer:  88%|████████▊ | 433/491 [02:18<00:19,  2.95it/s]
dSVA checkpoint transfer:  88%|████████▊ | 434/491 [02:19<00:19,  2.97it/s]
dSVA checkpoint transfer:  89%|████████▊ | 435/491 [02:19<00:18,  2.97it/s]
dSVA checkpoint transfer:  89%|████████▉ | 436/491 [02:19<00:18,  2.99it/s]
dSVA checkpoint transfer:  89%|████████▉ | 437/491 [02:20<00:18,  2.98it/s]
dSVA checkpoint transfer:  89%|████████▉ | 438/491 [02:20<00:17,  2.99it/s]
dSVA checkpoint transfer:  89%|████████▉ | 439/491 [02:21<00:17,  2.95it/s]
dSVA checkpoint transfer:  90%|████████▉ | 440/491 [02:21<00:17,  2.99it/s]
dSVA checkpoint transfer:  90%|████████▉ | 441/491 [02:21<00:16,  2.95it/s]
dSVA checkpoint transfer:  90%|█████████ | 442/491 [02:22<00:16,  2.99it/s]
dSVA checkpoint transfer:  90%|█████████ | 443/491 [02:22<00:16,  2.96it/s]
dSVA checkpoint transfer:  90%|█████████ | 444/491 [02:22<00:15,  3.13it/s]
dSVA checkpoint transfer:  91%|█████████ | 445/491 [02:22<00:13,  3.35it/s]
dSVA checkpoint transfer:  91%|█████████ | 446/491 [02:23<00:12,  3.53it/s]
dSVA checkpoint transfer:  91%|█████████ | 447/491 [02:23<00:12,  3.58it/s]
dSVA checkpoint transfer:  91%|█████████ | 448/491 [02:23<00:11,  3.70it/s]
dSVA checkpoint transfer:  91%|█████████▏| 449/491 [02:23<00:11,  3.76it/s]
dSVA checkpoint transfer:  92%|█████████▏| 450/491 [02:24<00:10,  3.84it/s]
dSVA checkpoint transfer:  92%|█████████▏| 451/491 [02:24<00:10,  3.91it/s]
dSVA checkpoint transfer:  92%|█████████▏| 452/491 [02:24<00:09,  3.91it/s]
dSVA checkpoint transfer:  92%|█████████▏| 453/491 [02:24<00:09,  3.98it/s]
dSVA checkpoint transfer:  92%|█████████▏| 454/491 [02:25<00:09,  4.04it/s]
dSVA checkpoint transfer:  93%|█████████▎| 455/491 [02:25<00:08,  4.04it/s]
dSVA checkpoint transfer:  93%|█████████▎| 456/491 [02:25<00:08,  4.06it/s]
dSVA checkpoint transfer:  93%|█████████▎| 457/491 [02:25<00:08,  4.06it/s]
dSVA checkpoint transfer:  93%|█████████▎| 458/491 [02:26<00:08,  4.05it/s]
dSVA checkpoint transfer:  93%|█████████▎| 459/491 [02:26<00:07,  4.05it/s]
dSVA checkpoint transfer:  94%|█████████▎| 460/491 [02:26<00:07,  4.00it/s]
dSVA checkpoint transfer:  94%|█████████▍| 461/491 [02:26<00:07,  3.96it/s]
dSVA checkpoint transfer:  94%|█████████▍| 462/491 [02:27<00:07,  3.93it/s]
dSVA checkpoint transfer:  94%|█████████▍| 463/491 [02:27<00:07,  3.95it/s]
dSVA checkpoint transfer:  95%|█████████▍| 464/491 [02:27<00:06,  3.87it/s]
dSVA checkpoint transfer:  95%|█████████▍| 465/491 [02:27<00:07,  3.54it/s]
dSVA checkpoint transfer:  95%|█████████▍| 466/491 [02:28<00:07,  3.35it/s]
dSVA checkpoint transfer:  95%|█████████▌| 467/491 [02:28<00:07,  3.04it/s]
dSVA checkpoint transfer:  95%|█████████▌| 468/491 [02:29<00:07,  3.04it/s]
dSVA checkpoint transfer:  96%|█████████▌| 469/491 [02:29<00:07,  2.96it/s]
dSVA checkpoint transfer:  96%|█████████▌| 470/491 [02:29<00:07,  2.99it/s]
dSVA checkpoint transfer:  96%|█████████▌| 471/491 [02:30<00:06,  2.97it/s]
dSVA checkpoint transfer:  96%|█████████▌| 472/491 [02:30<00:06,  2.88it/s]
dSVA checkpoint transfer:  96%|█████████▋| 473/491 [02:30<00:06,  2.87it/s]
dSVA checkpoint transfer:  97%|█████████▋| 474/491 [02:31<00:05,  2.92it/s]
dSVA checkpoint transfer:  97%|█████████▋| 475/491 [02:31<00:05,  2.89it/s]
dSVA checkpoint transfer:  97%|█████████▋| 476/491 [02:31<00:05,  2.90it/s]
dSVA checkpoint transfer:  97%|█████████▋| 477/491 [02:32<00:04,  2.92it/s]
dSVA checkpoint transfer:  97%|█████████▋| 478/491 [02:32<00:04,  2.91it/s]
dSVA checkpoint transfer:  98%|█████████▊| 479/491 [02:32<00:04,  2.94it/s]
dSVA checkpoint transfer:  98%|█████████▊| 480/491 [02:33<00:03,  2.99it/s]
dSVA checkpoint transfer:  98%|█████████▊| 481/491 [02:33<00:03,  3.19it/s]
dSVA checkpoint transfer:  98%|█████████▊| 482/491 [02:33<00:02,  3.39it/s]
dSVA checkpoint transfer:  98%|█████████▊| 483/491 [02:33<00:02,  3.55it/s]
dSVA checkpoint transfer:  99%|█████████▊| 484/491 [02:34<00:01,  3.68it/s]
dSVA checkpoint transfer:  99%|█████████▉| 485/491 [02:34<00:01,  3.80it/s]
dSVA checkpoint transfer:  99%|█████████▉| 486/491 [02:34<00:01,  3.87it/s]
dSVA checkpoint transfer:  99%|█████████▉| 487/491 [02:34<00:01,  3.86it/s]
dSVA checkpoint transfer:  99%|█████████▉| 488/491 [02:35<00:00,  3.94it/s]
dSVA checkpoint transfer: 100%|█████████▉| 489/491 [02:35<00:00,  3.98it/s]
dSVA checkpoint transfer: 100%|█████████▉| 490/491 [02:35<00:00,  3.87it/s]
dSVA checkpoint transfer: 100%|██████████| 491/491 [02:44<00:00,  2.86s/it]
dSVA checkpoint transfer: 100%|██████████| 491/491 [02:44<00:00,  2.98it/s]
| model | n | clean_acc | adv_acc | acc_drop | attack_success_rate |
| --- | ---: | ---: | ---: | ---: | ---: |
| resnet50 | 3925 | 87.34% | 28.89% | 58.45% | 68.35% |
| convnext_tiny | 3925 | 87.59% | 43.59% | 44.00% | 51.75% |
| vit_b_16 | 3925 | 91.85% | 20.99% | 70.85% | 77.70% |
| efficientnet_b0 | 3925 | 86.04% | 6.04% | 80.00% | 93.31% |
| swin_t | 3925 | 84.66% | 42.65% | 42.01% | 51.64% |

Mean transfer success: 68.55%
Max L_inf delta: 0.062744
Saved metrics to d:\Florent\Desktop\jepa-transfer-attacks\results\phase13_jepa_weight_ablation\seed_0\phase13_seed0_jepa_heavy_ep2_jw1_lr0p00005_eval.csv
Updated sweep summary: d:\Florent\Desktop\jepa-transfer-attacks\results\phase13_jepa_weight_ablation\seed_0\phase13_seed0_jepa_heavy_ep2_summary.csv

Saved sweep summary to d:\Florent\Desktop\jepa-transfer-attacks\results\phase13_jepa_weight_ablation\seed_0\phase13_seed0_jepa_heavy_ep2_summary.csv

Log: d:\Florent\Desktop\jepa-transfer-attacks\results\phase13_logs\sweep_dsva_jepa_finetune_2.log

c:\Users\Florent\anaconda3\python.exe scripts/sweep_dsva_jepa_finetune.py --train-root d:\Florent\Desktop\jepa-transfer-attacks\imagenette2-320\train --val-root d:\Florent\Desktop\jepa-transfer-attacks\imagenette2-320\val --init-checkpoint d:\Florent\Desktop\jepa-transfer-attacks\external\models\dSVA\model.pth --output-dir d:\Florent\Desktop\jepa-transfer-attacks\results\phase13_jepa_weight_ablation\seed_1 --run-prefix phase13_seed1_jepa_heavy_ep2 --configs 0.2:0.00005 0.3:0.00005 0.5:0.00005 1.0:0.00005 --limit 1000 --eval-limit 5000 --epochs 2 --batch-size 1 --eval-batch-size 8 --grad-accum-steps 8 --epsilon 0.06274509803921569 --output-mode scaled-delta --victims resnet50 convnext_tiny vit_b_16 efficientnet_b0 swin_t --device cuda --seed 1 --normalize-loss-weights --skip-existing --eval-amp --compile --compile-mode reduce-overhead
eckpoint transfer:  71%|███████   | 347/491 [01:34<00:36,  3.96it/s]
dSVA checkpoint transfer:  71%|███████   | 348/491 [01:34<00:35,  4.04it/s]
dSVA checkpoint transfer:  71%|███████   | 349/491 [01:35<00:35,  3.98it/s]
dSVA checkpoint transfer:  71%|███████▏  | 350/491 [01:35<00:35,  3.97it/s]
dSVA checkpoint transfer:  71%|███████▏  | 351/491 [01:35<00:34,  4.06it/s]
dSVA checkpoint transfer:  72%|███████▏  | 352/491 [01:35<00:34,  4.08it/s]
dSVA checkpoint transfer:  72%|███████▏  | 353/491 [01:36<00:34,  3.99it/s]
dSVA checkpoint transfer:  72%|███████▏  | 354/491 [01:36<00:34,  4.00it/s]
dSVA checkpoint transfer:  72%|███████▏  | 355/491 [01:36<00:33,  4.10it/s]
dSVA checkpoint transfer:  73%|███████▎  | 356/491 [01:36<00:32,  4.13it/s]
dSVA checkpoint transfer:  73%|███████▎  | 357/491 [01:36<00:32,  4.15it/s]
dSVA checkpoint transfer:  73%|███████▎  | 358/491 [01:37<00:31,  4.19it/s]
dSVA checkpoint transfer:  73%|███████▎  | 359/491 [01:37<00:31,  4.16it/s]
dSVA checkpoint transfer:  73%|███████▎  | 360/491 [01:37<00:31,  4.12it/s]
dSVA checkpoint transfer:  74%|███████▎  | 361/491 [01:37<00:31,  4.17it/s]
dSVA checkpoint transfer:  74%|███████▎  | 362/491 [01:38<00:31,  4.09it/s]
dSVA checkpoint transfer:  74%|███████▍  | 363/491 [01:38<00:31,  4.09it/s]
dSVA checkpoint transfer:  74%|███████▍  | 364/491 [01:38<00:30,  4.16it/s]
dSVA checkpoint transfer:  74%|███████▍  | 365/491 [01:38<00:31,  4.05it/s]
dSVA checkpoint transfer:  75%|███████▍  | 366/491 [01:39<00:30,  4.09it/s]
dSVA checkpoint transfer:  75%|███████▍  | 367/491 [01:39<00:29,  4.16it/s]
dSVA checkpoint transfer:  75%|███████▍  | 368/491 [01:39<00:29,  4.20it/s]
dSVA checkpoint transfer:  75%|███████▌  | 369/491 [01:39<00:29,  4.17it/s]
dSVA checkpoint transfer:  75%|███████▌  | 370/491 [01:40<00:28,  4.20it/s]
dSVA checkpoint transfer:  76%|███████▌  | 371/491 [01:40<00:28,  4.23it/s]
dSVA checkpoint transfer:  76%|███████▌  | 372/491 [01:40<00:28,  4.23it/s]
dSVA checkpoint transfer:  76%|███████▌  | 373/491 [01:40<00:28,  4.17it/s]
dSVA checkpoint transfer:  76%|███████▌  | 374/491 [01:41<00:27,  4.18it/s]
dSVA checkpoint transfer:  76%|███████▋  | 375/491 [01:41<00:27,  4.18it/s]
dSVA checkpoint transfer:  77%|███████▋  | 376/491 [01:41<00:27,  4.18it/s]
dSVA checkpoint transfer:  77%|███████▋  | 377/491 [01:41<00:28,  4.06it/s]
dSVA checkpoint transfer:  77%|███████▋  | 378/491 [01:42<00:27,  4.10it/s]
dSVA checkpoint transfer:  77%|███████▋  | 379/491 [01:42<00:27,  4.06it/s]
dSVA checkpoint transfer:  77%|███████▋  | 380/491 [01:42<00:27,  4.09it/s]
dSVA checkpoint transfer:  78%|███████▊  | 381/491 [01:42<00:26,  4.13it/s]
dSVA checkpoint transfer:  78%|███████▊  | 382/491 [01:42<00:25,  4.20it/s]
dSVA checkpoint transfer:  78%|███████▊  | 383/491 [01:43<00:25,  4.19it/s]
dSVA checkpoint transfer:  78%|███████▊  | 384/491 [01:43<00:25,  4.21it/s]
dSVA checkpoint transfer:  78%|███████▊  | 385/491 [01:43<00:24,  4.25it/s]
dSVA checkpoint transfer:  79%|███████▊  | 386/491 [01:43<00:24,  4.26it/s]
dSVA checkpoint transfer:  79%|███████▉  | 387/491 [01:44<00:24,  4.25it/s]
dSVA checkpoint transfer:  79%|███████▉  | 388/491 [01:44<00:24,  4.17it/s]
dSVA checkpoint transfer:  79%|███████▉  | 389/491 [01:44<00:24,  4.16it/s]
dSVA checkpoint transfer:  79%|███████▉  | 390/491 [01:44<00:24,  4.16it/s]
dSVA checkpoint transfer:  80%|███████▉  | 391/491 [01:45<00:23,  4.20it/s]
dSVA checkpoint transfer:  80%|███████▉  | 392/491 [01:45<00:23,  4.17it/s]
dSVA checkpoint transfer:  80%|████████  | 393/491 [01:45<00:23,  4.22it/s]
dSVA checkpoint transfer:  80%|████████  | 394/491 [01:45<00:23,  4.12it/s]
dSVA checkpoint transfer:  80%|████████  | 395/491 [01:46<00:23,  4.16it/s]
dSVA checkpoint transfer:  81%|████████  | 396/491 [01:46<00:22,  4.21it/s]
dSVA checkpoint transfer:  81%|████████  | 397/491 [01:46<00:22,  4.19it/s]
dSVA checkpoint transfer:  81%|████████  | 398/491 [01:46<00:22,  4.23it/s]
dSVA checkpoint transfer:  81%|████████▏ | 399/491 [01:47<00:21,  4.25it/s]
dSVA checkpoint transfer:  81%|████████▏ | 400/491 [01:47<00:21,  4.18it/s]
dSVA checkpoint transfer:  82%|████████▏ | 401/491 [01:47<00:21,  4.12it/s]
dSVA checkpoint transfer:  82%|████████▏ | 402/491 [01:47<00:21,  4.09it/s]
dSVA checkpoint transfer:  82%|████████▏ | 403/491 [01:48<00:21,  4.15it/s]
dSVA checkpoint transfer:  82%|████████▏ | 404/491 [01:48<00:20,  4.19it/s]
dSVA checkpoint transfer:  82%|████████▏ | 405/491 [01:48<00:20,  4.17it/s]
dSVA checkpoint transfer:  83%|████████▎ | 406/491 [01:48<00:20,  4.19it/s]
dSVA checkpoint transfer:  83%|████████▎ | 407/491 [01:48<00:20,  4.17it/s]
dSVA checkpoint transfer:  83%|████████▎ | 408/491 [01:49<00:20,  4.06it/s]
dSVA checkpoint transfer:  83%|████████▎ | 409/491 [01:49<00:20,  4.10it/s]
dSVA checkpoint transfer:  84%|████████▎ | 410/491 [01:49<00:19,  4.11it/s]
dSVA checkpoint transfer:  84%|████████▎ | 411/491 [01:49<00:19,  4.17it/s]
dSVA checkpoint transfer:  84%|████████▍ | 412/491 [01:50<00:18,  4.20it/s]
dSVA checkpoint transfer:  84%|████████▍ | 413/491 [01:50<00:18,  4.20it/s]
dSVA checkpoint transfer:  84%|████████▍ | 414/491 [01:50<00:18,  4.16it/s]
dSVA checkpoint transfer:  85%|████████▍ | 415/491 [01:50<00:18,  4.16it/s]
dSVA checkpoint transfer:  85%|████████▍ | 416/491 [01:51<00:17,  4.17it/s]
dSVA checkpoint transfer:  85%|████████▍ | 417/491 [01:51<00:17,  4.19it/s]
dSVA checkpoint transfer:  85%|████████▌ | 418/491 [01:51<00:17,  4.12it/s]
dSVA checkpoint transfer:  85%|████████▌ | 419/491 [01:51<00:18,  3.99it/s]
dSVA checkpoint transfer:  86%|████████▌ | 420/491 [01:52<00:17,  4.07it/s]
dSVA checkpoint transfer:  86%|████████▌ | 421/491 [01:52<00:16,  4.13it/s]
dSVA checkpoint transfer:  86%|████████▌ | 422/491 [01:52<00:16,  4.18it/s]
dSVA checkpoint transfer:  86%|████████▌ | 423/491 [01:52<00:16,  4.21it/s]
dSVA checkpoint transfer:  86%|████████▋ | 424/491 [01:53<00:15,  4.23it/s]
dSVA checkpoint transfer:  87%|████████▋ | 425/491 [01:53<00:15,  4.20it/s]
dSVA checkpoint transfer:  87%|████████▋ | 426/491 [01:53<00:15,  4.18it/s]
dSVA checkpoint transfer:  87%|████████▋ | 427/491 [01:53<00:15,  4.19it/s]

## Aggregate Results

In [10]:
run_checked([
    sys.executable,
    'scripts/analyze_phase11_scale_results.py',
    '--scale-root', 'results/phase13_jepa_weight_ablation',
    '--output-detail-csv', 'results/phase13_analysis/jepa_weight_detail.csv',
    '--output-aggregate-csv', 'results/phase13_analysis/jepa_weight_aggregate.csv',
])

aggregate = pd.read_csv(PHASE13_ANALYSIS_DIR / 'jepa_weight_aggregate.csv')
aggregate

c:\Users\Florent\anaconda3\python.exe scripts/analyze_phase11_scale_results.py --scale-root results/phase13_jepa_weight_ablation --output-detail-csv results/phase13_analysis/jepa_weight_detail.csv --output-aggregate-csv results/phase13_analysis/jepa_weight_aggregate.csv
Wrote detail CSV: results\phase13_analysis\jepa_weight_detail.csv
Wrote aggregate CSV: results\phase13_analysis\jepa_weight_aggregate.csv

Log: d:\Florent\Desktop\jepa-transfer-attacks\results\phase13_logs\analyze_phase11_scale_results_5.log

,objectives,run_type,jepa_weight,lr,epochs,train_limit,num_seeds,mean_transfer_success,std_transfer_success,resnet50_mean,resnet50_std,convnext_tiny_mean,convnext_tiny_std,vit_b_16_mean,vit_b_16_std,efficientnet_b0_mean,efficientnet_b0_std,swin_t_mean,swin_t_std
0,dino_mae,control,0.0,0.00005,2,1000,3,0.680356,0.010273,0.707118,0.020149,0.522106,0.015731,0.738141,0.002883,0.947608,0.008334,0.486809,0.010435
1,dino_mae_jepa,jepa,0.2,0.00005,2,1000,3,0.702227,0.008969,0.718300,0.022449,0.543242,0.008810,0.775589,0.002466,0.949176,0.009077,0.524827,0.007824
2,dino_mae_jepa,jepa,0.3,0.00005,2,1000,3,0.706548,0.007763,0.715869,0.023303,0.548866,0.007053,0.783819,0.001577,0.951535,0.008791,0.532651,0.001379
3,dino_mae_jepa,jepa,0.5,0.00005,2,1000,3,0.706443,0.009216,0.714119,0.024276,0.550999,0.006408,0.786408,0.005541,0.945232,0.011553,0.535460,0.008363
4,dino_mae_jepa,jepa,1.0,0.00005,2,1000,3,0.698749,0.014093,0.702742,0.023755,0.532480,0.015431,0.788534,0.011125,0.942853,0.010964,0.527134,0.010028

## Compare Against Untouched and Matched Controls

In [11]:
rows = aggregate.copy()
rows['mean_transfer_success'] = rows['mean_transfer_success'].astype(float)
controls = rows[rows['run_type'] == 'control'].set_index(['lr', 'epochs', 'train_limit'])['mean_transfer_success']

jepa = rows[rows['run_type'] == 'jepa'].copy()
jepa['control_mean'] = jepa.apply(
    lambda row: controls.loc[(row['lr'], row['epochs'], row['train_limit'])],
    axis=1,
)
jepa['gain_vs_control'] = jepa['mean_transfer_success'] - jepa['control_mean']
jepa['gain_vs_untouched'] = jepa['mean_transfer_success'] - untouched_mean

victim_baseline = untouched.set_index('model')['attack_success_rate'].to_dict()
for victim in VICTIMS:
    column = f'{victim}_mean'
    if column in jepa.columns and victim in victim_baseline:
        jepa[f'{victim}_gain_vs_untouched'] = jepa[column].astype(float) - victim_baseline[victim]

ordered = jepa.sort_values(['gain_vs_untouched', 'mean_transfer_success'], ascending=False)
ordered

,objectives,run_type,jepa_weight,lr,epochs,train_limit,num_seeds,mean_transfer_success,std_transfer_success,resnet50_mean,...,swin_t_mean,swin_t_std,control_mean,gain_vs_control,gain_vs_untouched,resnet50_gain_vs_untouched,convnext_tiny_gain_vs_untouched,vit_b_16_gain_vs_untouched,efficientnet_b0_gain_vs_untouched,swin_t_gain_vs_untouched
2,dino_mae_jepa,jepa,0.3,0.00005,2,1000,3,0.706548,0.007763,0.715869,...,0.532651,0.001379,0.680356,0.026192,0.012137,0.026837,-0.005526,0.010171,0.005429,0.023773
3,dino_mae_jepa,jepa,0.5,0.00005,2,1000,3,0.706443,0.009216,0.714119,...,0.535460,0.008363,0.680356,0.026087,0.012032,0.025087,-0.003393,0.012760,-0.000874,0.026582
1,dino_mae_jepa,jepa,0.2,0.00005,2,1000,3,0.702227,0.008969,0.718300,...,0.524827,0.007824,0.680356,0.021871,0.007816,0.029268,-0.011150,0.001941,0.003070,0.015949
4,dino_mae_jepa,jepa,1.0,0.00005,2,1000,3,0.698749,0.014093,0.702742,...,0.527134,0.010028,0.680356,0.018393,0.004338,0.013710,-0.021912,0.014886,-0.003253,0.018256

## Decision Read

In [12]:
best = ordered.iloc[0]
print('Best JEPA weight:', best['jepa_weight'])
print('Mean transfer:', f"{100 * best['mean_transfer_success']:.2f}%")
print('Gain vs untouched:', f"{100 * best['gain_vs_untouched']:+.2f} pts")
print('Gain vs matched control:', f"{100 * best['gain_vs_control']:+.2f} pts")

if best['gain_vs_untouched'] >= 0.01:
    print('Decision: strong enough to consider larger-scale validation.')
elif best['gain_vs_untouched'] > 0:
    print('Decision: positive but modest; fix continuation fidelity or add per-image complementarity before scaling.')
else:
    print('Decision: do not scale; JEPA did not beat the untouched released checkpoint on this panel.')

Best JEPA weight: 0.3
Mean transfer: 70.65%
Gain vs untouched: +1.21 pts
Gain vs matched control: +2.62 pts
Decision: strong enough to consider larger-scale validation.

## Package CSV Outputs

In [13]:
import tarfile

archive_path = REPO_ROOT / 'results' / 'phase13_csv_artifacts.tar.gz'
paths = list(PHASE13_OUTPUT_DIR.rglob('*.csv'))
paths += list(PHASE13_ANALYSIS_DIR.rglob('*.csv'))
smoke_csv = REPO_ROOT / 'results' / 'phase13_smoke_released_dsva_broader.csv'
if smoke_csv.exists():
    paths.append(smoke_csv)

with tarfile.open(archive_path, 'w:gz') as tar:
    for path in paths:
        tar.add(path, arcname=path.relative_to(REPO_ROOT))
print('Archive:', archive_path)

Archive: d:\Florent\Desktop\jepa-transfer-attacks\results\phase13_csv_artifacts.tar.gz