# Phase 11/12: I-JEPA Continuation Scaling Locally

Run this notebook on a local CUDA GPU. It keeps Phase 11 reproducible and adds Phase 12 as the lean kill test for tuned I-JEPA continuation.

Phase 11 tested:

- One-epoch weight sweep: `jepa_weight` 0.05, 0.1, 0.2 at `lr=5e-5`
- Longer continuation sweep: `jepa_weight=0.05`, epochs 2 and 3 at `lr=5e-5`

Phase 12 tests:

- Tuned longer continuation: `jepa_weight` 0.1 and 0.2, epochs 2 and 3 at `lr=5e-5`
- Matched DINO+MAE controls for each LR/epoch setting
- Winner-only broader victim panel: current victims plus `efficientnet_b0` and `swin_t`
- Seeds: 0, 1, 2
- Train limit: 1000 Imagenette train images
- Eval limit: 5000, covering full Imagenette validation
- Loss weights normalized with `--normalize-loss-weights`

The notebook uses `--skip-existing`, training AMP with GradScaler, eval AMP, and generator `torch.compile(..., mode="reduce-overhead")`. Evaluation victim compilation is left off by default on local 8 GB GPUs because it can spike memory.

## Setup

In [1]:
import torch
print('CUDA available:', torch.cuda.is_available())
if torch.cuda.is_available():
    print('GPU:', torch.cuda.get_device_name(0))

assert torch.cuda.is_available(), 'A local CUDA GPU is required for this experiment.'

CUDA available: True
GPU: NVIDIA GeForce RTX 2060 SUPER

In [2]:
from pathlib import Path

cwd = Path.cwd()
candidates = [cwd, cwd.parent]
REPO_ROOT = next(
    (path for path in candidates if (path / 'scripts' / 'sweep_dsva_jepa_finetune.py').exists()),
    None,
)
assert REPO_ROOT is not None, f'Could not find repo root from {cwd}'
print('Repo root:', REPO_ROOT)

Repo root: d:\Florent\Desktop\jepa-transfer-attacks

In [3]:
TRAIN_ROOT = REPO_ROOT / 'imagenette2-320' / 'train'
VAL_ROOT = REPO_ROOT / 'imagenette2-320' / 'val'
DSVA_CHECKPOINT = REPO_ROOT / 'external' / 'models' / 'dSVA' / 'model.pth'

assert TRAIN_ROOT.exists(), f'Missing training data: {TRAIN_ROOT}'
assert VAL_ROOT.exists(), f'Missing validation data: {VAL_ROOT}'
assert DSVA_CHECKPOINT.exists(), f'Missing dSVA checkpoint: {DSVA_CHECKPOINT}'

print('Train root:', TRAIN_ROOT)
print('Val root:', VAL_ROOT)
print('dSVA checkpoint:', DSVA_CHECKPOINT)

Train root: d:\Florent\Desktop\jepa-transfer-attacks\imagenette2-320\train
Val root: d:\Florent\Desktop\jepa-transfer-attacks\imagenette2-320\val
dSVA checkpoint: d:\Florent\Desktop\jepa-transfer-attacks\external\models\dSVA\model.pth

## Configuration

In [4]:
SEEDS = [0, 1, 2]
TRAIN_LIMIT = 1000
EVAL_LIMIT = 5000
LR = '0.00005'
EPSILON = '0.06274509803921569'
OUTPUT_MODE = 'scaled-delta'
CORE_VICTIMS = ['resnet50', 'convnext_tiny', 'vit_b_16']
BROADER_VICTIMS = [*CORE_VICTIMS, 'efficientnet_b0', 'swin_t']

PHASE11_OUTPUT_DIR = REPO_ROOT / 'results' / 'phase11_jepa_scale'
PHASE11_ANALYSIS_DIR = REPO_ROOT / 'results' / 'phase11_analysis'
PHASE12_OUTPUT_DIR = REPO_ROOT / 'results' / 'phase12_jepa_scale'
PHASE12_ANALYSIS_DIR = REPO_ROOT / 'results' / 'phase12_analysis'
PHASE12_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
PHASE12_ANALYSIS_DIR.mkdir(parents=True, exist_ok=True)

TRAIN_PERF_FLAGS = ['--compile', '--compile-mode', 'reduce-overhead']
EVAL_PERF_FLAGS = ['--eval-amp', *TRAIN_PERF_FLAGS]
# Keep eval victim compilation disabled by default on local 8 GB GPUs.
# Add '--eval-compile' to EVAL_PERF_FLAGS only if you have enough VRAM.

PHASE11_WEIGHT_CONFIGS = ['0.05:0.00005', '0.1:0.00005', '0.2:0.00005']
PHASE11_LONGER_RUNS = [
    {'label': 'jw0p05_ep2', 'configs': ['0.05:0.00005'], 'epochs': 2},
    {'label': 'jw0p05_ep3', 'configs': ['0.05:0.00005'], 'epochs': 3},
]
PHASE12_LONGER_RUNS = [
    {'label': 'jw0p1_0p2_ep2', 'configs': ['0.1:0.00005', '0.2:0.00005'], 'epochs': 2},
    {'label': 'jw0p1_0p2_ep3', 'configs': ['0.1:0.00005', '0.2:0.00005'], 'epochs': 3},
]

print('Phase 11 output dir:', PHASE11_OUTPUT_DIR)
print('Phase 12 output dir:', PHASE12_OUTPUT_DIR)
print('Performance flags:', EVAL_PERF_FLAGS)
print('Core victims:', CORE_VICTIMS)
print('Broader victims:', BROADER_VICTIMS)

Phase 11 output dir: d:\Florent\Desktop\jepa-transfer-attacks\results\phase11_jepa_scale
Phase 12 output dir: d:\Florent\Desktop\jepa-transfer-attacks\results\phase12_jepa_scale
Performance flags: ['--eval-amp', '--compile', '--compile-mode', 'reduce-overhead']
Core victims: ['resnet50', 'convnext_tiny', 'vit_b_16']
Broader victims: ['resnet50', 'convnext_tiny', 'vit_b_16', 'efficientnet_b0', 'swin_t']

## Optional Smoke Test

In [ ]:
import subprocess, sys

smoke_cmd = [
    sys.executable,
    'scripts/run_dsva_checkpoint_attack.py',
    '--data-root', str(VAL_ROOT),
    '--checkpoint', str(DSVA_CHECKPOINT),
    '--output-mode', 'adv',
    '--limit', '16',
    '--batch-size', '8',
    '--epsilon', EPSILON,
    '--victims', *CORE_VICTIMS,
    '--device', 'cuda',
    '--output-csv', 'results/phase12_smoke_released_dsva.csv',
    '--amp',
]
print(' '.join(smoke_cmd))
subprocess.run(smoke_cmd, cwd=REPO_ROOT, check=True)

In [10]:
import subprocess, sys
from pathlib import Path
import pandas as pd

def run_checked(cmd):
    print('\n' + ' '.join(map(str, cmd)), flush=True)
    log_dir = REPO_ROOT / 'results' / 'phase12_logs'
    log_dir.mkdir(parents=True, exist_ok=True)
    log_path = log_dir / (Path(str(cmd[1])).stem + '_' + str(len(list(log_dir.glob('*.log')))).replace(' ', '_') + '.log')
    with log_path.open('w', encoding='utf-8', errors='replace') as handle:
        result = subprocess.run(
            cmd,
            cwd=REPO_ROOT,
            text=True,
            stdout=handle,
            stderr=subprocess.STDOUT,
        )
    text = log_path.read_text(encoding='utf-8', errors='replace')
    print(text[-12000:])
    print('Log:', log_path)
    if result.returncode != 0:
        raise RuntimeError(f"Command failed with exit code {result.returncode}: {' '.join(map(str, cmd))}")
    return result

## Optional Phase 11 Reproduction: One-Epoch JEPA Weight Sweep

In [ ]:
for seed in SEEDS:
    seed_dir = PHASE11_OUTPUT_DIR / f'seed_{seed}'
    seed_dir.mkdir(parents=True, exist_ok=True)
    cmd = [
        sys.executable,
        'scripts/sweep_dsva_jepa_finetune.py',
        '--train-root', str(TRAIN_ROOT),
        '--val-root', str(VAL_ROOT),
        '--init-checkpoint', str(DSVA_CHECKPOINT),
        '--output-dir', str(seed_dir),
        '--run-prefix', f'phase11_seed{seed}_weight_sweep',
        '--configs', *PHASE11_WEIGHT_CONFIGS,
        '--limit', str(TRAIN_LIMIT),
        '--eval-limit', str(EVAL_LIMIT),
        '--epochs', '1',
        '--batch-size', '1',
        '--eval-batch-size', '8',
        '--grad-accum-steps', '8',
        '--epsilon', EPSILON,
        '--output-mode', OUTPUT_MODE,
        '--victims', *CORE_VICTIMS,
        '--device', 'cuda',
        '--seed', str(seed),
        '--normalize-loss-weights',
        '--skip-existing',
        *EVAL_PERF_FLAGS,
    ]
    run_checked(cmd)

## Optional Phase 11 Reproduction: Longer Continuation Sweep

In [ ]:
for run in PHASE11_LONGER_RUNS:
    for seed in SEEDS:
        seed_dir = PHASE11_OUTPUT_DIR / f'seed_{seed}'
        seed_dir.mkdir(parents=True, exist_ok=True)
        cmd = [
            sys.executable,
            'scripts/sweep_dsva_jepa_finetune.py',
            '--train-root', str(TRAIN_ROOT),
            '--val-root', str(VAL_ROOT),
            '--init-checkpoint', str(DSVA_CHECKPOINT),
            '--output-dir', str(seed_dir),
            '--run-prefix', f"phase11_seed{seed}_{run['label']}",
            '--configs', *run['configs'],
            '--limit', str(TRAIN_LIMIT),
            '--eval-limit', str(EVAL_LIMIT),
            '--epochs', str(run['epochs']),
            '--batch-size', '1',
            '--eval-batch-size', '8',
            '--grad-accum-steps', '8',
            '--epsilon', EPSILON,
            '--output-mode', OUTPUT_MODE,
            '--victims', *CORE_VICTIMS,
            '--device', 'cuda',
            '--seed', str(seed),
            '--normalize-loss-weights',
            '--skip-existing',
            *EVAL_PERF_FLAGS,
        ]
        run_checked(cmd)

## Aggregate Phase 11 Results

In [ ]:
run_checked([
    sys.executable,
    'scripts/analyze_phase11_scale_results.py',
    '--scale-root', 'results/phase11_jepa_scale',
    '--output-detail-csv', 'results/phase11_analysis/jepa_scale_detail.csv',
    '--output-aggregate-csv', 'results/phase11_analysis/jepa_scale_aggregate.csv',
])

pd.read_csv(PHASE11_ANALYSIS_DIR / 'jepa_scale_aggregate.csv')

## Phase 12: Tuned Longer Continuation

In [8]:
for run in PHASE12_LONGER_RUNS:
    for seed in SEEDS:
        seed_dir = PHASE12_OUTPUT_DIR / f'seed_{seed}'
        seed_dir.mkdir(parents=True, exist_ok=True)
        cmd = [
            sys.executable,
            'scripts/sweep_dsva_jepa_finetune.py',
            '--train-root', str(TRAIN_ROOT),
            '--val-root', str(VAL_ROOT),
            '--init-checkpoint', str(DSVA_CHECKPOINT),
            '--output-dir', str(seed_dir),
            '--run-prefix', f"phase12_seed{seed}_{run['label']}",
            '--configs', *run['configs'],
            '--limit', str(TRAIN_LIMIT),
            '--eval-limit', str(EVAL_LIMIT),
            '--epochs', str(run['epochs']),
            '--batch-size', '1',
            '--eval-batch-size', '8',
            '--grad-accum-steps', '8',
            '--epsilon', EPSILON,
            '--output-mode', OUTPUT_MODE,
            '--victims', *CORE_VICTIMS,
            '--device', 'cuda',
            '--seed', str(seed),
            '--normalize-loss-weights',
            '--skip-existing',
            *EVAL_PERF_FLAGS,
        ]
        run_checked(cmd)

c:\Users\Florent\anaconda3\python.exe scripts/sweep_dsva_jepa_finetune.py --train-root d:\Florent\Desktop\jepa-transfer-attacks\imagenette2-320\train --val-root d:\Florent\Desktop\jepa-transfer-attacks\imagenette2-320\val --init-checkpoint d:\Florent\Desktop\jepa-transfer-attacks\external\models\dSVA\model.pth --output-dir d:\Florent\Desktop\jepa-transfer-attacks\results\phase12_jepa_scale\seed_0 --run-prefix phase12_seed0_jw0p1_0p2_ep2 --configs 0.1:0.00005 0.2:0.00005 --limit 1000 --eval-limit 5000 --epochs 2 --batch-size 1 --eval-batch-size 8 --grad-accum-steps 8 --epsilon 0.06274509803921569 --output-mode scaled-delta --victims resnet50 convnext_tiny vit_b_16 --device cuda --seed 0 --normalize-loss-weights --skip-existing --eval-amp --compile --compile-mode reduce-overhead
int transfer:  70%|███████   | 345/491 [01:30<00:36,  4.04it/s]
dSVA checkpoint transfer:  70%|███████   | 346/491 [01:30<00:33,  4.28it/s]
dSVA checkpoint transfer:  71%|███████   | 347/491 [01:30<00:36,  3.98it/s]
dSVA checkpoint transfer:  71%|███████   | 348/491 [01:31<00:34,  4.12it/s]
dSVA checkpoint transfer:  71%|███████   | 349/491 [01:31<00:33,  4.23it/s]
dSVA checkpoint transfer:  71%|███████▏  | 350/491 [01:31<00:32,  4.39it/s]
dSVA checkpoint transfer:  71%|███████▏  | 351/491 [01:31<00:31,  4.45it/s]
dSVA checkpoint transfer:  72%|███████▏  | 352/491 [01:31<00:29,  4.64it/s]
dSVA checkpoint transfer:  72%|███████▏  | 353/491 [01:32<00:32,  4.29it/s]
dSVA checkpoint transfer:  72%|███████▏  | 354/491 [01:32<00:33,  4.08it/s]
dSVA checkpoint transfer:  72%|███████▏  | 355/491 [01:32<00:32,  4.20it/s]
dSVA checkpoint transfer:  73%|███████▎  | 356/491 [01:32<00:30,  4.36it/s]
dSVA checkpoint transfer:  73%|███████▎  | 357/491 [01:33<00:30,  4.44it/s]
dSVA checkpoint transfer:  73%|███████▎  | 358/491 [01:33<00:29,  4.49it/s]
dSVA checkpoint transfer:  73%|███████▎  | 359/491 [01:33<00:29,  4.40it/s]
dSVA checkpoint transfer:  73%|███████▎  | 360/491 [01:33<00:32,  4.00it/s]
dSVA checkpoint transfer:  74%|███████▎  | 361/491 [01:34<00:31,  4.08it/s]
dSVA checkpoint transfer:  74%|███████▎  | 362/491 [01:34<00:30,  4.22it/s]
dSVA checkpoint transfer:  74%|███████▍  | 363/491 [01:34<00:29,  4.33it/s]
dSVA checkpoint transfer:  74%|███████▍  | 364/491 [01:34<00:29,  4.31it/s]
dSVA checkpoint transfer:  74%|███████▍  | 365/491 [01:34<00:28,  4.44it/s]
dSVA checkpoint transfer:  75%|███████▍  | 366/491 [01:35<00:26,  4.68it/s]
dSVA checkpoint transfer:  75%|███████▍  | 367/491 [01:35<00:28,  4.41it/s]
dSVA checkpoint transfer:  75%|███████▍  | 368/491 [01:35<00:26,  4.61it/s]
dSVA checkpoint transfer:  75%|███████▌  | 369/491 [01:35<00:26,  4.65it/s]
dSVA checkpoint transfer:  75%|███████▌  | 370/491 [01:35<00:25,  4.81it/s]
dSVA checkpoint transfer:  76%|███████▌  | 371/491 [01:36<00:29,  4.14it/s]
dSVA checkpoint transfer:  76%|███████▌  | 372/491 [01:36<00:30,  3.84it/s]
dSVA checkpoint transfer:  76%|███████▌  | 373/491 [01:36<00:28,  4.19it/s]
dSVA checkpoint transfer:  76%|███████▌  | 374/491 [01:36<00:26,  4.39it/s]
dSVA checkpoint transfer:  76%|███████▋  | 375/491 [01:37<00:25,  4.58it/s]
dSVA checkpoint transfer:  77%|███████▋  | 376/491 [01:37<00:25,  4.57it/s]
dSVA checkpoint transfer:  77%|███████▋  | 377/491 [01:37<00:24,  4.59it/s]
dSVA checkpoint transfer:  77%|███████▋  | 378/491 [01:37<00:26,  4.24it/s]
dSVA checkpoint transfer:  77%|███████▋  | 379/491 [01:38<00:25,  4.35it/s]
dSVA checkpoint transfer:  77%|███████▋  | 380/491 [01:38<00:24,  4.48it/s]
dSVA checkpoint transfer:  78%|███████▊  | 381/491 [01:38<00:24,  4.50it/s]
dSVA checkpoint transfer:  78%|███████▊  | 382/491 [01:38<00:25,  4.25it/s]
dSVA checkpoint transfer:  78%|███████▊  | 383/491 [01:39<00:27,  3.91it/s]
dSVA checkpoint transfer:  78%|███████▊  | 384/491 [01:39<00:26,  3.97it/s]
dSVA checkpoint transfer:  78%|███████▊  | 385/491 [01:39<00:26,  3.97it/s]
dSVA checkpoint transfer:  79%|███████▊  | 386/491 [01:39<00:25,  4.11it/s]
dSVA checkpoint transfer:  79%|███████▉  | 387/491 [01:40<00:30,  3.40it/s]
dSVA checkpoint transfer:  79%|███████▉  | 388/491 [01:40<00:27,  3.71it/s]
dSVA checkpoint transfer:  79%|███████▉  | 389/491 [01:40<00:26,  3.91it/s]
dSVA checkpoint transfer:  79%|███████▉  | 390/491 [01:40<00:23,  4.26it/s]
dSVA checkpoint transfer:  80%|███████▉  | 391/491 [01:41<00:22,  4.53it/s]
dSVA checkpoint transfer:  80%|███████▉  | 392/491 [01:41<00:23,  4.27it/s]
dSVA checkpoint transfer:  80%|████████  | 393/491 [01:41<00:22,  4.27it/s]
dSVA checkpoint transfer:  80%|████████  | 394/491 [01:41<00:22,  4.31it/s]
dSVA checkpoint transfer:  80%|████████  | 395/491 [01:42<00:22,  4.20it/s]
dSVA checkpoint transfer:  81%|████████  | 396/491 [01:42<00:21,  4.45it/s]
dSVA checkpoint transfer:  81%|████████  | 397/491 [01:42<00:20,  4.63it/s]
dSVA checkpoint transfer:  81%|████████  | 398/491 [01:42<00:21,  4.30it/s]
dSVA checkpoint transfer:  81%|████████▏ | 399/491 [01:42<00:21,  4.26it/s]
dSVA checkpoint transfer:  81%|████████▏ | 400/491 [01:43<00:20,  4.51it/s]
dSVA checkpoint transfer:  82%|████████▏ | 401/491 [01:43<00:19,  4.64it/s]
dSVA checkpoint transfer:  82%|████████▏ | 402/491 [01:43<00:18,  4.74it/s]
dSVA checkpoint transfer:  82%|████████▏ | 403/491 [01:43<00:17,  4.90it/s]
dSVA checkpoint transfer:  82%|████████▏ | 404/491 [01:43<00:17,  4.88it/s]
dSVA checkpoint transfer:  82%|████████▏ | 405/491 [01:44<00:17,  4.90it/s]
dSVA checkpoint transfer:  83%|████████▎ | 406/491 [01:44<00:17,  4.97it/s]
dSVA checkpoint transfer:  83%|████████▎ | 407/491 [01:44<00:16,  5.09it/s]
dSVA checkpoint transfer:  83%|████████▎ | 408/491 [01:44<00:16,  5.07it/s]
dSVA checkpoint transfer:  83%|████████▎ | 409/491 [01:44<00:16,  4.93it/s]
dSVA checkpoint transfer:  84%|████████▎ | 410/491 [01:45<00:16,  4.96it/s]
dSVA checkpoint transfer:  84%|████████▎ | 411/491 [01:45<00:16,  4.94it/s]
dSVA checkpoint transfer:  84%|████████▍ | 412/491 [01:45<00:15,  5.02it/s]
dSVA checkpoint transfer:  84%|████████▍ | 413/491 [01:45<00:15,  5.12it/s]
dSVA checkpoint transfer:  84%|████████▍ | 414/491 [01:45<00:16,  4.72it/s]
dSVA checkpoint transfer:  85%|████████▍ | 415/491 [01:46<00:16,  4.65it/s]
dSVA checkpoint transfer:  85%|████████▍ | 416/491 [01:46<00:15,  4.80it/s]
dSVA checkpoint transfer:  85%|████████▍ | 417/491 [01:46<00:14,  4.97it/s]
dSVA checkpoint transfer:  85%|████████▌ | 418/491 [01:46<00:14,  4.93it/s]
dSVA checkpoint transfer:  85%|████████▌ | 419/491 [01:46<00:14,  5.05it/s]
dSVA checkpoint transfer:  86%|████████▌ | 420/491 [01:47<00:14,  5.05it/s]
dSVA checkpoint transfer:  86%|████████▌ | 421/491 [01:47<00:13,  5.15it/s]
dSVA checkpoint transfer:  86%|████████▌ | 422/491 [01:47<00:13,  5.17it/s]
dSVA checkpoint transfer:  86%|████████▌ | 423/491 [01:47<00:14,  4.73it/s]
dSVA checkpoint transfer:  86%|████████▋ | 424/491 [01:47<00:14,  4.71it/s]
dSVA checkpoint transfer:  87%|████████▋ | 425/491 [01:48<00:13,  4.79it/s]
dSVA checkpoint transfer:  87%|████████▋ | 426/491 [01:48<00:13,  4.93it/s]
dSVA checkpoint transfer:  87%|████████▋ | 427/491 [01:48<00:12,  4.99it/s]
dSVA checkpoint transfer:  87%|████████▋ | 428/491 [01:48<00:12,  4.89it/s]
dSVA checkpoint transfer:  87%|████████▋ | 429/491 [01:49<00:13,  4.62it/s]
dSVA checkpoint transfer:  88%|████████▊ | 430/491 [01:49<00:12,  4.77it/s]
dSVA checkpoint transfer:  88%|████████▊ | 431/491 [01:49<00:12,  4.93it/s]
dSVA checkpoint transfer:  88%|████████▊ | 432/491 [01:49<00:11,  5.10it/s]
dSVA checkpoint transfer:  88%|████████▊ | 433/491 [01:49<00:11,  5.10it/s]
dSVA checkpoint transfer:  88%|████████▊ | 434/491 [01:49<00:11,  5.11it/s]
dSVA checkpoint transfer:  89%|████████▊ | 435/491 [01:50<00:10,  5.18it/s]
dSVA checkpoint transfer:  89%|████████▉ | 436/491 [01:50<00:10,  5.22it/s]
dSVA checkpoint transfer:  89%|████████▉ | 437/491 [01:50<00:10,  5.15it/s]
dSVA checkpoint transfer:  89%|████████▉ | 438/491 [01:50<00:10,  5.20it/s]
dSVA checkpoint transfer:  89%|████████▉ | 439/491 [01:50<00:10,  5.03it/s]
dSVA checkpoint transfer:  90%|████████▉ | 440/491 [01:51<00:10,  5.06it/s]
dSVA checkpoint transfer:  90%|████████▉ | 441/491 [01:51<00:10,  4.78it/s]
dSVA checkpoint transfer:  90%|█████████ | 442/491 [01:51<00:10,  4.74it/s]
dSVA checkpoint transfer:  90%|█████████ | 443/491 [01:51<00:11,  4.27it/s]
dSVA checkpoint transfer:  90%|█████████ | 444/491 [01:52<00:11,  4.10it/s]
dSVA checkpoint transfer:  91%|█████████ | 445/491 [01:52<00:11,  4.08it/s]
dSVA checkpoint transfer:  91%|█████████ | 446/491 [01:52<00:11,  4.06it/s]
dSVA checkpoint transfer:  91%|█████████ | 447/491 [01:52<00:10,  4.07it/s]
dSVA checkpoint transfer:  91%|█████████ | 448/491 [01:53<00:10,  4.05it/s]
dSVA checkpoint transfer:  91%|█████████▏| 449/491 [01:53<00:10,  3.92it/s]
dSVA checkpoint transfer:  92%|█████████▏| 450/491 [01:53<00:09,  4.20it/s]
dSVA checkpoint transfer:  92%|█████████▏| 451/491 [01:53<00:09,  4.29it/s]
dSVA checkpoint transfer:  92%|█████████▏| 452/491 [01:54<00:08,  4.49it/s]
dSVA checkpoint transfer:  92%|█████████▏| 453/491 [01:54<00:08,  4.70it/s]
dSVA checkpoint transfer:  92%|█████████▏| 454/491 [01:54<00:07,  4.67it/s]
dSVA checkpoint transfer:  93%|█████████▎| 455/491 [01:54<00:07,  4.83it/s]
dSVA checkpoint transfer:  93%|█████████▎| 456/491 [01:54<00:07,  4.99it/s]
dSVA checkpoint transfer:  93%|█████████▎| 457/491 [01:55<00:06,  4.98it/s]
dSVA checkpoint transfer:  93%|█████████▎| 458/491 [01:55<00:06,  5.03it/s]
dSVA checkpoint transfer:  93%|█████████▎| 459/491 [01:55<00:06,  5.12it/s]
dSVA checkpoint transfer:  94%|█████████▎| 460/491 [01:55<00:06,  5.11it/s]
dSVA checkpoint transfer:  94%|█████████▍| 461/491 [01:55<00:06,  4.92it/s]
dSVA checkpoint transfer:  94%|█████████▍| 462/491 [01:56<00:05,  4.86it/s]
dSVA checkpoint transfer:  94%|█████████▍| 463/491 [01:56<00:05,  4.88it/s]
dSVA checkpoint transfer:  95%|█████████▍| 464/491 [01:56<00:05,  4.76it/s]
dSVA checkpoint transfer:  95%|█████████▍| 465/491 [01:56<00:05,  4.91it/s]
dSVA checkpoint transfer:  95%|█████████▍| 466/491 [01:56<00:05,  4.71it/s]
dSVA checkpoint transfer:  95%|█████████▌| 467/491 [01:57<00:04,  4.82it/s]
dSVA checkpoint transfer:  95%|█████████▌| 468/491 [01:57<00:04,  4.91it/s]
dSVA checkpoint transfer:  96%|█████████▌| 469/491 [01:57<00:04,  5.02it/s]
dSVA checkpoint transfer:  96%|█████████▌| 470/491 [01:57<00:04,  4.91it/s]
dSVA checkpoint transfer:  96%|█████████▌| 471/491 [01:57<00:04,  4.96it/s]
dSVA checkpoint transfer:  96%|█████████▌| 472/491 [01:58<00:03,  4.90it/s]
dSVA checkpoint transfer:  96%|█████████▋| 473/491 [01:58<00:03,  4.88it/s]
dSVA checkpoint transfer:  97%|█████████▋| 474/491 [01:58<00:03,  4.62it/s]
dSVA checkpoint transfer:  97%|█████████▋| 475/491 [01:58<00:03,  4.72it/s]
dSVA checkpoint transfer:  97%|█████████▋| 476/491 [01:58<00:03,  4.77it/s]
dSVA checkpoint transfer:  97%|█████████▋| 477/491 [01:59<00:02,  4.80it/s]
dSVA checkpoint transfer:  97%|█████████▋| 478/491 [01:59<00:02,  4.90it/s]
dSVA checkpoint transfer:  98%|█████████▊| 479/491 [01:59<00:02,  4.54it/s]
dSVA checkpoint transfer:  98%|█████████▊| 480/491 [01:59<00:02,  4.28it/s]
dSVA checkpoint transfer:  98%|█████████▊| 481/491 [02:00<00:02,  4.26it/s]
dSVA checkpoint transfer:  98%|█████████▊| 482/491 [02:00<00:01,  4.51it/s]
dSVA checkpoint transfer:  98%|█████████▊| 483/491 [02:00<00:01,  4.57it/s]
dSVA checkpoint transfer:  99%|█████████▊| 484/491 [02:00<00:01,  4.77it/s]
dSVA checkpoint transfer:  99%|█████████▉| 485/491 [02:00<00:01,  4.96it/s]
dSVA checkpoint transfer:  99%|█████████▉| 486/491 [02:01<00:00,  5.04it/s]
dSVA checkpoint transfer:  99%|█████████▉| 487/491 [02:01<00:00,  5.09it/s]
dSVA checkpoint transfer:  99%|█████████▉| 488/491 [02:01<00:00,  5.12it/s]
dSVA checkpoint transfer: 100%|█████████▉| 489/491 [02:01<00:00,  5.01it/s]
dSVA checkpoint transfer: 100%|█████████▉| 490/491 [02:01<00:00,  4.81it/s]
dSVA checkpoint transfer: 100%|██████████| 491/491 [02:05<00:00,  1.11s/it]
dSVA checkpoint transfer: 100%|██████████| 491/491 [02:05<00:00,  3.92it/s]
| model | n | clean_acc | adv_acc | acc_drop | attack_success_rate |
| --- | ---: | ---: | ---: | ---: | ---: |
| resnet50 | 3925 | 87.34% | 27.67% | 59.67% | 69.72% |
| convnext_tiny | 3925 | 87.59% | 42.24% | 45.35% | 53.14% |
| vit_b_16 | 3925 | 91.85% | 21.68% | 70.17% | 76.84% |

Mean transfer success: 66.57%
Max L_inf delta: 0.062744
Saved metrics to d:\Florent\Desktop\jepa-transfer-attacks\results\phase12_jepa_scale\seed_0\phase12_seed0_jw0p1_0p2_ep2_jw0p2_lr0p00005_eval.csv
Updated sweep summary: d:\Florent\Desktop\jepa-transfer-attacks\results\phase12_jepa_scale\seed_0\phase12_seed0_jw0p1_0p2_ep2_summary.csv

Saved sweep summary to d:\Florent\Desktop\jepa-transfer-attacks\results\phase12_jepa_scale\seed_0\phase12_seed0_jw0p1_0p2_ep2_summary.csv

Log: d:\Florent\Desktop\jepa-transfer-attacks\results\phase12_logs\sweep_dsva_jepa_finetune_0.log

c:\Users\Florent\anaconda3\python.exe scripts/sweep_dsva_jepa_finetune.py --train-root d:\Florent\Desktop\jepa-transfer-attacks\imagenette2-320\train --val-root d:\Florent\Desktop\jepa-transfer-attacks\imagenette2-320\val --init-checkpoint d:\Florent\Desktop\jepa-transfer-attacks\external\models\dSVA\model.pth --output-dir d:\Florent\Desktop\jepa-transfer-attacks\results\phase12_jepa_scale\seed_1 --run-prefix phase12_seed1_jw0p1_0p2_ep2 --configs 0.1:0.00005 0.2:0.00005 --limit 1000 --eval-limit 5000 --epochs 2 --batch-size 1 --eval-batch-size 8 --grad-accum-steps 8 --epsilon 0.06274509803921569 --output-mode scaled-delta --victims resnet50 convnext_tiny vit_b_16 --device cuda --seed 1 --normalize-loss-weights --skip-existing --eval-amp --compile --compile-mode reduce-overhead
int transfer:  70%|███████   | 345/491 [01:33<00:36,  4.04it/s]
dSVA checkpoint transfer:  70%|███████   | 346/491 [01:33<00:35,  4.05it/s]
dSVA checkpoint transfer:  71%|███████   | 347/491 [01:33<00:35,  4.04it/s]
dSVA checkpoint transfer:  71%|███████   | 348/491 [01:33<00:35,  4.04it/s]
dSVA checkpoint transfer:  71%|███████   | 349/491 [01:34<00:35,  3.99it/s]
dSVA checkpoint transfer:  71%|███████▏  | 350/491 [01:34<00:35,  4.01it/s]
dSVA checkpoint transfer:  71%|███████▏  | 351/491 [01:34<00:34,  4.02it/s]
dSVA checkpoint transfer:  72%|███████▏  | 352/491 [01:34<00:34,  4.01it/s]
dSVA checkpoint transfer:  72%|███████▏  | 353/491 [01:35<00:34,  4.03it/s]
dSVA checkpoint transfer:  72%|███████▏  | 354/491 [01:35<00:34,  4.03it/s]
dSVA checkpoint transfer:  72%|███████▏  | 355/491 [01:35<00:33,  4.04it/s]
dSVA checkpoint transfer:  73%|███████▎  | 356/491 [01:35<00:33,  4.05it/s]
dSVA checkpoint transfer:  73%|███████▎  | 357/491 [01:35<00:33,  4.02it/s]
dSVA checkpoint transfer:  73%|███████▎  | 358/491 [01:36<00:33,  4.02it/s]
dSVA checkpoint transfer:  73%|███████▎  | 359/491 [01:36<00:32,  4.03it/s]
dSVA checkpoint transfer:  73%|███████▎  | 360/491 [01:36<00:32,  4.06it/s]
dSVA checkpoint transfer:  74%|███████▎  | 361/491 [01:36<00:32,  4.04it/s]
dSVA checkpoint transfer:  74%|███████▎  | 362/491 [01:37<00:31,  4.07it/s]
dSVA checkpoint transfer:  74%|███████▍  | 363/491 [01:37<00:31,  4.08it/s]
dSVA checkpoint transfer:  74%|███████▍  | 364/491 [01:37<00:31,  4.05it/s]
dSVA checkpoint transfer:  74%|███████▍  | 365/491 [01:37<00:31,  4.05it/s]
dSVA checkpoint transfer:  75%|███████▍  | 366/491 [01:38<00:29,  4.31it/s]
dSVA checkpoint transfer:  75%|███████▍  | 367/491 [01:38<00:27,  4.50it/s]
dSVA checkpoint transfer:  75%|███████▍  | 368/491 [01:38<00:26,  4.65it/s]
dSVA checkpoint transfer:  75%|███████▌  | 369/491 [01:38<00:25,  4.75it/s]
dSVA checkpoint transfer:  75%|███████▌  | 370/491 [01:38<00:25,  4.79it/s]
dSVA checkpoint transfer:  76%|███████▌  | 371/491 [01:39<00:24,  4.87it/s]
dSVA checkpoint transfer:  76%|███████▌  | 372/491 [01:39<00:24,  4.90it/s]
dSVA checkpoint transfer:  76%|███████▌  | 373/491 [01:39<00:23,  4.92it/s]
dSVA checkpoint transfer:  76%|███████▌  | 374/491 [01:39<00:23,  4.95it/s]
dSVA checkpoint transfer:  76%|███████▋  | 375/491 [01:39<00:23,  4.98it/s]
dSVA checkpoint transfer:  77%|███████▋  | 376/491 [01:40<00:23,  5.00it/s]
dSVA checkpoint transfer:  77%|███████▋  | 377/491 [01:40<00:22,  4.99it/s]
dSVA checkpoint transfer:  77%|███████▋  | 378/491 [01:40<00:22,  4.98it/s]
dSVA checkpoint transfer:  77%|███████▋  | 379/491 [01:40<00:22,  5.00it/s]
dSVA checkpoint transfer:  77%|███████▋  | 380/491 [01:40<00:22,  4.99it/s]
dSVA checkpoint transfer:  78%|███████▊  | 381/491 [01:41<00:22,  4.99it/s]
dSVA checkpoint transfer:  78%|███████▊  | 382/491 [01:41<00:21,  4.99it/s]
dSVA checkpoint transfer:  78%|███████▊  | 383/491 [01:41<00:21,  4.96it/s]
dSVA checkpoint transfer:  78%|███████▊  | 384/491 [01:41<00:21,  4.98it/s]
dSVA checkpoint transfer:  78%|███████▊  | 385/491 [01:41<00:21,  5.00it/s]
dSVA checkpoint transfer:  79%|███████▊  | 386/491 [01:42<00:20,  5.01it/s]
dSVA checkpoint transfer:  79%|███████▉  | 387/491 [01:42<00:20,  5.03it/s]
dSVA checkpoint transfer:  79%|███████▉  | 388/491 [01:42<00:20,  5.03it/s]
dSVA checkpoint transfer:  79%|███████▉  | 389/491 [01:42<00:20,  5.01it/s]
dSVA checkpoint transfer:  79%|███████▉  | 390/491 [01:42<00:20,  5.01it/s]
dSVA checkpoint transfer:  80%|███████▉  | 391/491 [01:43<00:19,  5.06it/s]
dSVA checkpoint transfer:  80%|███████▉  | 392/491 [01:43<00:19,  5.04it/s]
dSVA checkpoint transfer:  80%|████████  | 393/491 [01:43<00:19,  5.03it/s]
dSVA checkpoint transfer:  80%|████████  | 394/491 [01:43<00:19,  5.00it/s]
dSVA checkpoint transfer:  80%|████████  | 395/491 [01:43<00:19,  5.03it/s]
dSVA checkpoint transfer:  81%|████████  | 396/491 [01:44<00:18,  5.08it/s]
dSVA checkpoint transfer:  81%|████████  | 397/491 [01:44<00:18,  5.13it/s]
dSVA checkpoint transfer:  81%|████████  | 398/491 [01:44<00:18,  5.15it/s]
dSVA checkpoint transfer:  81%|████████▏ | 399/491 [01:44<00:17,  5.19it/s]
dSVA checkpoint transfer:  81%|████████▏ | 400/491 [01:44<00:17,  5.12it/s]
dSVA checkpoint transfer:  82%|████████▏ | 401/491 [01:45<00:17,  5.13it/s]
dSVA checkpoint transfer:  82%|████████▏ | 402/491 [01:45<00:17,  5.11it/s]
dSVA checkpoint transfer:  82%|████████▏ | 403/491 [01:45<00:17,  5.11it/s]
dSVA checkpoint transfer:  82%|████████▏ | 404/491 [01:45<00:16,  5.16it/s]
dSVA checkpoint transfer:  82%|████████▏ | 405/491 [01:45<00:16,  5.11it/s]
dSVA checkpoint transfer:  83%|████████▎ | 406/491 [01:46<00:16,  5.12it/s]
dSVA checkpoint transfer:  83%|████████▎ | 407/491 [01:46<00:16,  5.12it/s]
dSVA checkpoint transfer:  83%|████████▎ | 408/491 [01:46<00:16,  5.08it/s]
dSVA checkpoint transfer:  83%|████████▎ | 409/491 [01:46<00:16,  5.11it/s]
dSVA checkpoint transfer:  84%|████████▎ | 410/491 [01:46<00:15,  5.11it/s]
dSVA checkpoint transfer:  84%|████████▎ | 411/491 [01:47<00:15,  5.12it/s]
dSVA checkpoint transfer:  84%|████████▍ | 412/491 [01:47<00:15,  5.13it/s]
dSVA checkpoint transfer:  84%|████████▍ | 413/491 [01:47<00:15,  5.16it/s]
dSVA checkpoint transfer:  84%|████████▍ | 414/491 [01:47<00:14,  5.14it/s]
dSVA checkpoint transfer:  85%|████████▍ | 415/491 [01:47<00:14,  5.12it/s]
dSVA checkpoint transfer:  85%|████████▍ | 416/491 [01:48<00:14,  5.05it/s]
dSVA checkpoint transfer:  85%|████████▍ | 417/491 [01:48<00:14,  5.05it/s]
dSVA checkpoint transfer:  85%|████████▌ | 418/491 [01:48<00:14,  5.08it/s]
dSVA checkpoint transfer:  85%|████████▌ | 419/491 [01:48<00:14,  5.08it/s]
dSVA checkpoint transfer:  86%|████████▌ | 420/491 [01:48<00:14,  5.02it/s]
dSVA checkpoint transfer:  86%|████████▌ | 421/491 [01:49<00:14,  5.00it/s]
dSVA checkpoint transfer:  86%|████████▌ | 422/491 [01:49<00:13,  5.01it/s]
dSVA checkpoint transfer:  86%|████████▌ | 423/491 [01:49<00:13,  5.02it/s]
dSVA checkpoint transfer:  86%|████████▋ | 424/491 [01:49<00:13,  5.09it/s]
dSVA checkpoint transfer:  87%|████████▋ | 425/491 [01:49<00:13,  5.07it/s]
dSVA checkpoint transfer:  87%|████████▋ | 426/491 [01:50<00:12,  5.09it/s]
dSVA checkpoint transfer:  87%|████████▋ | 427/491 [01:50<00:12,  5.12it/s]

## Aggregate Phase 12 Tuned Results

In [11]:
run_checked([
    sys.executable,
    'scripts/analyze_phase11_scale_results.py',
    '--scale-root', 'results/phase12_jepa_scale',
    '--output-detail-csv', 'results/phase12_analysis/jepa_scale_detail.csv',
    '--output-aggregate-csv', 'results/phase12_analysis/jepa_scale_aggregate.csv',
])

phase12_aggregate = pd.read_csv(PHASE12_ANALYSIS_DIR / 'jepa_scale_aggregate.csv')
phase12_aggregate

c:\Users\Florent\anaconda3\python.exe scripts/analyze_phase11_scale_results.py --scale-root results/phase12_jepa_scale --output-detail-csv results/phase12_analysis/jepa_scale_detail.csv --output-aggregate-csv results/phase12_analysis/jepa_scale_aggregate.csv
Wrote detail CSV: results\phase12_analysis\jepa_scale_detail.csv
Wrote aggregate CSV: results\phase12_analysis\jepa_scale_aggregate.csv

Log: d:\Florent\Desktop\jepa-transfer-attacks\results\phase12_logs\analyze_phase11_scale_results_7.log

,objectives,run_type,jepa_weight,lr,epochs,train_limit,num_seeds,mean_transfer_success,std_transfer_success,resnet50_mean,resnet50_std,convnext_tiny_mean,convnext_tiny_std,vit_b_16_mean,vit_b_16_std
0,dino_mae,control,0.0,0.00005,2,1000,3,0.656445,0.010692,0.708965,0.017252,0.522785,0.014889,0.737587,0.004813
1,dino_mae,control,0.0,0.00005,3,1000,3,0.665626,0.001798,0.732886,0.005793,0.547023,0.004127,0.716967,0.003286
2,dino_mae_jepa,jepa,0.1,0.00005,2,1000,3,0.672113,0.009240,0.715772,0.017998,0.538685,0.007624,0.761882,0.004208
3,dino_mae_jepa,jepa,0.1,0.00005,3,1000,3,0.674524,0.003878,0.732789,0.000505,0.542564,0.006454,0.748220,0.010083
4,dino_mae_jepa,jepa,0.2,0.00005,2,1000,3,0.680230,0.013038,0.717717,0.023081,0.546830,0.013351,0.776144,0.008377
5,dino_mae_jepa,jepa,0.2,0.00005,3,1000,3,0.681542,0.002566,0.734734,0.003671,0.542370,0.002607,0.767523,0.004586

## Pick Phase 12 Winner

In [12]:
def pick_best_jepa_config(aggregate):
    rows = aggregate.copy()
    rows['mean_transfer_success'] = rows['mean_transfer_success'].astype(float)
    controls = rows[rows['run_type'] == 'control'].set_index(['lr', 'epochs', 'train_limit'])['mean_transfer_success']
    candidates = rows[rows['run_type'] == 'jepa'].copy()
    candidates['control_mean'] = candidates.apply(
        lambda row: controls.loc[(row['lr'], row['epochs'], row['train_limit'])],
        axis=1,
    )
    candidates['matched_gain'] = candidates['mean_transfer_success'] - candidates['control_mean']
    return candidates.sort_values(['matched_gain', 'mean_transfer_success'], ascending=False).iloc[0]

best = pick_best_jepa_config(phase12_aggregate)
BEST_JEPA_WEIGHT = str(best['jepa_weight'])
BEST_LR = str(best['lr'])
BEST_EPOCHS = int(best['epochs'])
BEST_CONFIG = f'{BEST_JEPA_WEIGHT}:{BEST_LR}'
print('Best tuned config:', BEST_CONFIG, 'epochs:', BEST_EPOCHS, 'matched gain:', f"{best['matched_gain']:.4f}")
best.to_frame().T

Best tuned config: 0.2:5e-05 epochs: 2 matched gain: 0.0238

,objectives,run_type,jepa_weight,lr,epochs,train_limit,num_seeds,mean_transfer_success,std_transfer_success,resnet50_mean,resnet50_std,convnext_tiny_mean,convnext_tiny_std,vit_b_16_mean,vit_b_16_std,control_mean,matched_gain
4,dino_mae_jepa,jepa,0.2,0.00005,2,1000,3,0.68023,0.013038,0.717717,0.023081,0.54683,0.013351,0.776144,0.008377,0.656445,0.023785

## Phase 12: Winner-Only Broader Victim Panel

In [13]:
for seed in SEEDS:
    seed_dir = PHASE12_OUTPUT_DIR / f'seed_{seed}'
    seed_dir.mkdir(parents=True, exist_ok=True)
    cmd = [
        sys.executable,
        'scripts/sweep_dsva_jepa_finetune.py',
        '--train-root', str(TRAIN_ROOT),
        '--val-root', str(VAL_ROOT),
        '--init-checkpoint', str(DSVA_CHECKPOINT),
        '--output-dir', str(seed_dir),
        '--run-prefix', f'phase12_seed{seed}_broader_victims_ep{BEST_EPOCHS}_jw{BEST_JEPA_WEIGHT.replace(".", "p")}',
        '--configs', BEST_CONFIG,
        '--limit', str(TRAIN_LIMIT),
        '--eval-limit', str(EVAL_LIMIT),
        '--epochs', str(BEST_EPOCHS),
        '--batch-size', '1',
        '--eval-batch-size', '8',
        '--grad-accum-steps', '8',
        '--epsilon', EPSILON,
        '--output-mode', OUTPUT_MODE,
        '--victims', *BROADER_VICTIMS,
        '--device', 'cuda',
        '--seed', str(seed),
        '--normalize-loss-weights',
        '--skip-existing',
        *EVAL_PERF_FLAGS,
    ]
    run_checked(cmd)

c:\Users\Florent\anaconda3\python.exe scripts/sweep_dsva_jepa_finetune.py --train-root d:\Florent\Desktop\jepa-transfer-attacks\imagenette2-320\train --val-root d:\Florent\Desktop\jepa-transfer-attacks\imagenette2-320\val --init-checkpoint d:\Florent\Desktop\jepa-transfer-attacks\external\models\dSVA\model.pth --output-dir d:\Florent\Desktop\jepa-transfer-attacks\results\phase12_jepa_scale\seed_0 --run-prefix phase12_seed0_broader_victims_ep2_jw0p2 --configs 0.2:5e-05 --limit 1000 --eval-limit 5000 --epochs 2 --batch-size 1 --eval-batch-size 8 --grad-accum-steps 8 --epsilon 0.06274509803921569 --output-mode scaled-delta --victims resnet50 convnext_tiny vit_b_16 efficientnet_b0 swin_t --device cuda --seed 0 --normalize-loss-weights --skip-existing --eval-amp --compile --compile-mode reduce-overhead
int transfer:  71%|███████   | 347/491 [01:51<00:35,  4.06it/s]
dSVA checkpoint transfer:  71%|███████   | 348/491 [01:51<00:35,  4.06it/s]
dSVA checkpoint transfer:  71%|███████   | 349/491 [01:51<00:35,  4.05it/s]
dSVA checkpoint transfer:  71%|███████▏  | 350/491 [01:51<00:34,  4.06it/s]
dSVA checkpoint transfer:  71%|███████▏  | 351/491 [01:52<00:34,  4.04it/s]
dSVA checkpoint transfer:  72%|███████▏  | 352/491 [01:52<00:34,  4.04it/s]
dSVA checkpoint transfer:  72%|███████▏  | 353/491 [01:52<00:34,  4.05it/s]
dSVA checkpoint transfer:  72%|███████▏  | 354/491 [01:52<00:33,  4.06it/s]
dSVA checkpoint transfer:  72%|███████▏  | 355/491 [01:52<00:33,  4.07it/s]
dSVA checkpoint transfer:  73%|███████▎  | 356/491 [01:53<00:33,  4.05it/s]
dSVA checkpoint transfer:  73%|███████▎  | 357/491 [01:53<00:33,  4.04it/s]
dSVA checkpoint transfer:  73%|███████▎  | 358/491 [01:53<00:32,  4.05it/s]
dSVA checkpoint transfer:  73%|███████▎  | 359/491 [01:53<00:32,  4.08it/s]
dSVA checkpoint transfer:  73%|███████▎  | 360/491 [01:54<00:32,  4.09it/s]
dSVA checkpoint transfer:  74%|███████▎  | 361/491 [01:54<00:31,  4.10it/s]
dSVA checkpoint transfer:  74%|███████▎  | 362/491 [01:54<00:31,  4.09it/s]
dSVA checkpoint transfer:  74%|███████▍  | 363/491 [01:54<00:31,  4.07it/s]
dSVA checkpoint transfer:  74%|███████▍  | 364/491 [01:55<00:31,  4.09it/s]
dSVA checkpoint transfer:  74%|███████▍  | 365/491 [01:55<00:30,  4.07it/s]
dSVA checkpoint transfer:  75%|███████▍  | 366/491 [01:55<00:30,  4.07it/s]
dSVA checkpoint transfer:  75%|███████▍  | 367/491 [01:55<00:30,  4.07it/s]
dSVA checkpoint transfer:  75%|███████▍  | 368/491 [01:56<00:30,  4.08it/s]
dSVA checkpoint transfer:  75%|███████▌  | 369/491 [01:56<00:29,  4.07it/s]
dSVA checkpoint transfer:  75%|███████▌  | 370/491 [01:56<00:29,  4.07it/s]
dSVA checkpoint transfer:  76%|███████▌  | 371/491 [01:56<00:29,  4.06it/s]
dSVA checkpoint transfer:  76%|███████▌  | 372/491 [01:57<00:29,  4.07it/s]
dSVA checkpoint transfer:  76%|███████▌  | 373/491 [01:57<00:28,  4.07it/s]
dSVA checkpoint transfer:  76%|███████▌  | 374/491 [01:57<00:28,  4.08it/s]
dSVA checkpoint transfer:  76%|███████▋  | 375/491 [01:57<00:28,  4.08it/s]
dSVA checkpoint transfer:  77%|███████▋  | 376/491 [01:58<00:28,  4.05it/s]
dSVA checkpoint transfer:  77%|███████▋  | 377/491 [01:58<00:28,  4.05it/s]
dSVA checkpoint transfer:  77%|███████▋  | 378/491 [01:58<00:27,  4.06it/s]
dSVA checkpoint transfer:  77%|███████▋  | 379/491 [01:58<00:27,  4.05it/s]
dSVA checkpoint transfer:  77%|███████▋  | 380/491 [01:59<00:27,  4.06it/s]
dSVA checkpoint transfer:  78%|███████▊  | 381/491 [01:59<00:26,  4.08it/s]
dSVA checkpoint transfer:  78%|███████▊  | 382/491 [01:59<00:26,  4.04it/s]
dSVA checkpoint transfer:  78%|███████▊  | 383/491 [01:59<00:26,  4.06it/s]
dSVA checkpoint transfer:  78%|███████▊  | 384/491 [02:00<00:26,  4.07it/s]
dSVA checkpoint transfer:  78%|███████▊  | 385/491 [02:00<00:26,  4.07it/s]
dSVA checkpoint transfer:  79%|███████▊  | 386/491 [02:00<00:25,  4.09it/s]
dSVA checkpoint transfer:  79%|███████▉  | 387/491 [02:00<00:25,  4.09it/s]
dSVA checkpoint transfer:  79%|███████▉  | 388/491 [02:01<00:25,  4.08it/s]
dSVA checkpoint transfer:  79%|███████▉  | 389/491 [02:01<00:25,  4.07it/s]
dSVA checkpoint transfer:  79%|███████▉  | 390/491 [02:01<00:24,  4.08it/s]
dSVA checkpoint transfer:  80%|███████▉  | 391/491 [02:01<00:24,  4.09it/s]
dSVA checkpoint transfer:  80%|███████▉  | 392/491 [02:02<00:24,  4.08it/s]
dSVA checkpoint transfer:  80%|████████  | 393/491 [02:02<00:23,  4.08it/s]
dSVA checkpoint transfer:  80%|████████  | 394/491 [02:02<00:23,  4.09it/s]
dSVA checkpoint transfer:  80%|████████  | 395/491 [02:02<00:23,  4.09it/s]
dSVA checkpoint transfer:  81%|████████  | 396/491 [02:03<00:23,  4.09it/s]
dSVA checkpoint transfer:  81%|████████  | 397/491 [02:03<00:23,  4.08it/s]
dSVA checkpoint transfer:  81%|████████  | 398/491 [02:03<00:22,  4.10it/s]
dSVA checkpoint transfer:  81%|████████▏ | 399/491 [02:03<00:22,  4.10it/s]
dSVA checkpoint transfer:  81%|████████▏ | 400/491 [02:04<00:22,  4.08it/s]
dSVA checkpoint transfer:  82%|████████▏ | 401/491 [02:04<00:22,  4.05it/s]
dSVA checkpoint transfer:  82%|████████▏ | 402/491 [02:04<00:22,  4.04it/s]
dSVA checkpoint transfer:  82%|████████▏ | 403/491 [02:04<00:21,  4.04it/s]
dSVA checkpoint transfer:  82%|████████▏ | 404/491 [02:05<00:21,  4.07it/s]
dSVA checkpoint transfer:  82%|████████▏ | 405/491 [02:05<00:21,  4.06it/s]
dSVA checkpoint transfer:  83%|████████▎ | 406/491 [02:05<00:20,  4.05it/s]
dSVA checkpoint transfer:  83%|████████▎ | 407/491 [02:05<00:20,  4.03it/s]
dSVA checkpoint transfer:  83%|████████▎ | 408/491 [02:06<00:20,  4.05it/s]
dSVA checkpoint transfer:  83%|████████▎ | 409/491 [02:06<00:20,  4.01it/s]
dSVA checkpoint transfer:  84%|████████▎ | 410/491 [02:06<00:20,  4.01it/s]
dSVA checkpoint transfer:  84%|████████▎ | 411/491 [02:06<00:19,  4.04it/s]
dSVA checkpoint transfer:  84%|████████▍ | 412/491 [02:07<00:19,  4.04it/s]
dSVA checkpoint transfer:  84%|████████▍ | 413/491 [02:07<00:19,  4.08it/s]
dSVA checkpoint transfer:  84%|████████▍ | 414/491 [02:07<00:18,  4.08it/s]
dSVA checkpoint transfer:  85%|████████▍ | 415/491 [02:07<00:18,  4.04it/s]
dSVA checkpoint transfer:  85%|████████▍ | 416/491 [02:07<00:18,  4.04it/s]
dSVA checkpoint transfer:  85%|████████▍ | 417/491 [02:08<00:18,  4.02it/s]
dSVA checkpoint transfer:  85%|████████▌ | 418/491 [02:08<00:18,  4.04it/s]
dSVA checkpoint transfer:  85%|████████▌ | 419/491 [02:08<00:17,  4.06it/s]
dSVA checkpoint transfer:  86%|████████▌ | 420/491 [02:08<00:17,  4.06it/s]
dSVA checkpoint transfer:  86%|████████▌ | 421/491 [02:09<00:17,  4.06it/s]
dSVA checkpoint transfer:  86%|████████▌ | 422/491 [02:09<00:16,  4.08it/s]
dSVA checkpoint transfer:  86%|████████▌ | 423/491 [02:09<00:16,  4.09it/s]
dSVA checkpoint transfer:  86%|████████▋ | 424/491 [02:09<00:16,  4.11it/s]
dSVA checkpoint transfer:  87%|████████▋ | 425/491 [02:10<00:16,  4.11it/s]
dSVA checkpoint transfer:  87%|████████▋ | 426/491 [02:10<00:15,  4.12it/s]
dSVA checkpoint transfer:  87%|████████▋ | 427/491 [02:10<00:15,  4.03it/s]
dSVA checkpoint transfer:  87%|████████▋ | 428/491 [02:10<00:15,  4.05it/s]
dSVA checkpoint transfer:  87%|████████▋ | 429/491 [02:11<00:15,  4.07it/s]
dSVA checkpoint transfer:  88%|████████▊ | 430/491 [02:11<00:14,  4.08it/s]
dSVA checkpoint transfer:  88%|████████▊ | 431/491 [02:11<00:14,  4.06it/s]
dSVA checkpoint transfer:  88%|████████▊ | 432/491 [02:11<00:14,  4.07it/s]
dSVA checkpoint transfer:  88%|████████▊ | 433/491 [02:12<00:14,  4.05it/s]
dSVA checkpoint transfer:  88%|████████▊ | 434/491 [02:12<00:14,  4.06it/s]
dSVA checkpoint transfer:  89%|████████▊ | 435/491 [02:12<00:13,  4.06it/s]
dSVA checkpoint transfer:  89%|████████▉ | 436/491 [02:12<00:13,  3.94it/s]
dSVA checkpoint transfer:  89%|████████▉ | 437/491 [02:13<00:13,  3.99it/s]
dSVA checkpoint transfer:  89%|████████▉ | 438/491 [02:13<00:13,  3.98it/s]
dSVA checkpoint transfer:  89%|████████▉ | 439/491 [02:13<00:12,  4.00it/s]
dSVA checkpoint transfer:  90%|████████▉ | 440/491 [02:13<00:12,  4.03it/s]
dSVA checkpoint transfer:  90%|████████▉ | 441/491 [02:14<00:12,  4.04it/s]
dSVA checkpoint transfer:  90%|█████████ | 442/491 [02:14<00:12,  4.05it/s]
dSVA checkpoint transfer:  90%|█████████ | 443/491 [02:14<00:11,  4.07it/s]
dSVA checkpoint transfer:  90%|█████████ | 444/491 [02:14<00:11,  4.09it/s]
dSVA checkpoint transfer:  91%|█████████ | 445/491 [02:15<00:11,  4.04it/s]
dSVA checkpoint transfer:  91%|█████████ | 446/491 [02:15<00:11,  4.04it/s]
dSVA checkpoint transfer:  91%|█████████ | 447/491 [02:15<00:10,  4.05it/s]
dSVA checkpoint transfer:  91%|█████████ | 448/491 [02:15<00:10,  4.06it/s]
dSVA checkpoint transfer:  91%|█████████▏| 449/491 [02:16<00:10,  4.07it/s]
dSVA checkpoint transfer:  92%|█████████▏| 450/491 [02:16<00:10,  4.08it/s]
dSVA checkpoint transfer:  92%|█████████▏| 451/491 [02:16<00:09,  4.08it/s]
dSVA checkpoint transfer:  92%|█████████▏| 452/491 [02:16<00:09,  4.08it/s]
dSVA checkpoint transfer:  92%|█████████▏| 453/491 [02:17<00:09,  4.10it/s]
dSVA checkpoint transfer:  92%|█████████▏| 454/491 [02:17<00:09,  4.06it/s]
dSVA checkpoint transfer:  93%|█████████▎| 455/491 [02:17<00:08,  4.06it/s]
dSVA checkpoint transfer:  93%|█████████▎| 456/491 [02:17<00:08,  4.05it/s]
dSVA checkpoint transfer:  93%|█████████▎| 457/491 [02:18<00:08,  4.07it/s]
dSVA checkpoint transfer:  93%|█████████▎| 458/491 [02:18<00:08,  4.08it/s]
dSVA checkpoint transfer:  93%|█████████▎| 459/491 [02:18<00:07,  4.06it/s]
dSVA checkpoint transfer:  94%|█████████▎| 460/491 [02:18<00:07,  3.91it/s]
dSVA checkpoint transfer:  94%|█████████▍| 461/491 [02:19<00:07,  3.93it/s]
dSVA checkpoint transfer:  94%|█████████▍| 462/491 [02:19<00:07,  3.96it/s]
dSVA checkpoint transfer:  94%|█████████▍| 463/491 [02:19<00:07,  3.96it/s]
dSVA checkpoint transfer:  95%|█████████▍| 464/491 [02:19<00:06,  3.98it/s]
dSVA checkpoint transfer:  95%|█████████▍| 465/491 [02:20<00:06,  3.99it/s]
dSVA checkpoint transfer:  95%|█████████▍| 466/491 [02:20<00:06,  4.01it/s]
dSVA checkpoint transfer:  95%|█████████▌| 467/491 [02:20<00:05,  4.04it/s]
dSVA checkpoint transfer:  95%|█████████▌| 468/491 [02:20<00:05,  4.06it/s]
dSVA checkpoint transfer:  96%|█████████▌| 469/491 [02:21<00:05,  4.05it/s]
dSVA checkpoint transfer:  96%|█████████▌| 470/491 [02:21<00:05,  4.01it/s]
dSVA checkpoint transfer:  96%|█████████▌| 471/491 [02:21<00:04,  4.04it/s]
dSVA checkpoint transfer:  96%|█████████▌| 472/491 [02:21<00:04,  4.04it/s]
dSVA checkpoint transfer:  96%|█████████▋| 473/491 [02:22<00:04,  4.05it/s]
dSVA checkpoint transfer:  97%|█████████▋| 474/491 [02:22<00:04,  3.94it/s]
dSVA checkpoint transfer:  97%|█████████▋| 475/491 [02:22<00:04,  3.99it/s]
dSVA checkpoint transfer:  97%|█████████▋| 476/491 [02:22<00:03,  4.02it/s]
dSVA checkpoint transfer:  97%|█████████▋| 477/491 [02:23<00:03,  4.04it/s]
dSVA checkpoint transfer:  97%|█████████▋| 478/491 [02:23<00:03,  4.02it/s]
dSVA checkpoint transfer:  98%|█████████▊| 479/491 [02:23<00:02,  4.02it/s]
dSVA checkpoint transfer:  98%|█████████▊| 480/491 [02:23<00:02,  4.03it/s]
dSVA checkpoint transfer:  98%|█████████▊| 481/491 [02:24<00:02,  4.02it/s]
dSVA checkpoint transfer:  98%|█████████▊| 482/491 [02:24<00:02,  3.99it/s]
dSVA checkpoint transfer:  98%|█████████▊| 483/491 [02:24<00:01,  4.00it/s]
dSVA checkpoint transfer:  99%|█████████▊| 484/491 [02:24<00:01,  4.03it/s]
dSVA checkpoint transfer:  99%|█████████▉| 485/491 [02:25<00:01,  4.03it/s]
dSVA checkpoint transfer:  99%|█████████▉| 486/491 [02:25<00:01,  4.05it/s]
dSVA checkpoint transfer:  99%|█████████▉| 487/491 [02:25<00:00,  4.06it/s]
dSVA checkpoint transfer:  99%|█████████▉| 488/491 [02:25<00:00,  4.08it/s]
dSVA checkpoint transfer: 100%|█████████▉| 489/491 [02:26<00:00,  4.07it/s]
dSVA checkpoint transfer: 100%|█████████▉| 490/491 [02:26<00:00,  4.07it/s]
dSVA checkpoint transfer: 100%|██████████| 491/491 [02:33<00:00,  2.43s/it]
dSVA checkpoint transfer: 100%|██████████| 491/491 [02:33<00:00,  3.19it/s]
| model | n | clean_acc | adv_acc | acc_drop | attack_success_rate |
| --- | ---: | ---: | ---: | ---: | ---: |
| resnet50 | 3925 | 87.34% | 27.59% | 59.75% | 69.81% |
| convnext_tiny | 3925 | 87.59% | 42.04% | 45.55% | 53.37% |
| vit_b_16 | 3925 | 91.85% | 20.84% | 71.01% | 77.75% |
| efficientnet_b0 | 3925 | 86.04% | 5.12% | 80.92% | 94.34% |
| swin_t | 3925 | 84.66% | 41.78% | 42.88% | 52.69% |

Mean transfer success: 69.59%
Max L_inf delta: 0.062744
Saved metrics to d:\Florent\Desktop\jepa-transfer-attacks\results\phase12_jepa_scale\seed_0\phase12_seed0_broader_victims_ep2_jw0p2_jw0p2_lr0p00005_eval.csv
Updated sweep summary: d:\Florent\Desktop\jepa-transfer-attacks\results\phase12_jepa_scale\seed_0\phase12_seed0_broader_victims_ep2_jw0p2_summary.csv

Saved sweep summary to d:\Florent\Desktop\jepa-transfer-attacks\results\phase12_jepa_scale\seed_0\phase12_seed0_broader_victims_ep2_jw0p2_summary.csv

Log: d:\Florent\Desktop\jepa-transfer-attacks\results\phase12_logs\sweep_dsva_jepa_finetune_8.log

c:\Users\Florent\anaconda3\python.exe scripts/sweep_dsva_jepa_finetune.py --train-root d:\Florent\Desktop\jepa-transfer-attacks\imagenette2-320\train --val-root d:\Florent\Desktop\jepa-transfer-attacks\imagenette2-320\val --init-checkpoint d:\Florent\Desktop\jepa-transfer-attacks\external\models\dSVA\model.pth --output-dir d:\Florent\Desktop\jepa-transfer-attacks\results\phase12_jepa_scale\seed_1 --run-prefix phase12_seed1_broader_victims_ep2_jw0p2 --configs 0.2:5e-05 --limit 1000 --eval-limit 5000 --epochs 2 --batch-size 1 --eval-batch-size 8 --grad-accum-steps 8 --epsilon 0.06274509803921569 --output-mode scaled-delta --victims resnet50 convnext_tiny vit_b_16 efficientnet_b0 swin_t --device cuda --seed 1 --normalize-loss-weights --skip-existing --eval-amp --compile --compile-mode reduce-overhead
int transfer:  71%|███████   | 347/491 [02:16<00:53,  2.69it/s]
dSVA checkpoint transfer:  71%|███████   | 348/491 [02:16<00:52,  2.73it/s]
dSVA checkpoint transfer:  71%|███████   | 349/491 [02:17<00:50,  2.81it/s]
dSVA checkpoint transfer:  71%|███████▏  | 350/491 [02:17<00:50,  2.77it/s]
dSVA checkpoint transfer:  71%|███████▏  | 351/491 [02:17<00:50,  2.78it/s]
dSVA checkpoint transfer:  72%|███████▏  | 352/491 [02:18<00:51,  2.70it/s]
dSVA checkpoint transfer:  72%|███████▏  | 353/491 [02:19<01:07,  2.04it/s]
dSVA checkpoint transfer:  72%|███████▏  | 354/491 [02:19<01:03,  2.16it/s]
dSVA checkpoint transfer:  72%|███████▏  | 355/491 [02:19<01:02,  2.16it/s]
dSVA checkpoint transfer:  73%|███████▎  | 356/491 [02:20<00:54,  2.48it/s]
dSVA checkpoint transfer:  73%|███████▎  | 357/491 [02:20<00:54,  2.48it/s]
dSVA checkpoint transfer:  73%|███████▎  | 358/491 [02:20<00:51,  2.60it/s]
dSVA checkpoint transfer:  73%|███████▎  | 359/491 [02:22<01:18,  1.68it/s]
dSVA checkpoint transfer:  73%|███████▎  | 360/491 [02:22<01:12,  1.80it/s]
dSVA checkpoint transfer:  74%|███████▎  | 361/491 [02:22<01:03,  2.06it/s]
dSVA checkpoint transfer:  74%|███████▎  | 362/491 [02:23<00:55,  2.31it/s]
dSVA checkpoint transfer:  74%|███████▍  | 363/491 [02:23<00:50,  2.52it/s]
dSVA checkpoint transfer:  74%|███████▍  | 364/491 [02:23<00:48,  2.63it/s]
dSVA checkpoint transfer:  74%|███████▍  | 365/491 [02:24<00:45,  2.77it/s]
dSVA checkpoint transfer:  75%|███████▍  | 366/491 [02:24<00:48,  2.59it/s]
dSVA checkpoint transfer:  75%|███████▍  | 367/491 [02:24<00:48,  2.58it/s]
dSVA checkpoint transfer:  75%|███████▍  | 368/491 [02:25<00:43,  2.82it/s]
dSVA checkpoint transfer:  75%|███████▌  | 369/491 [02:25<00:42,  2.89it/s]
dSVA checkpoint transfer:  75%|███████▌  | 370/491 [02:25<00:39,  3.08it/s]
dSVA checkpoint transfer:  76%|███████▌  | 371/491 [02:26<00:45,  2.62it/s]
dSVA checkpoint transfer:  76%|███████▌  | 372/491 [02:27<01:05,  1.82it/s]
dSVA checkpoint transfer:  76%|███████▌  | 373/491 [02:27<01:09,  1.69it/s]
dSVA checkpoint transfer:  76%|███████▌  | 374/491 [02:28<00:58,  2.01it/s]
dSVA checkpoint transfer:  76%|███████▋  | 375/491 [02:28<00:52,  2.20it/s]
dSVA checkpoint transfer:  77%|███████▋  | 376/491 [02:28<00:46,  2.46it/s]
dSVA checkpoint transfer:  77%|███████▋  | 377/491 [02:29<00:45,  2.49it/s]
dSVA checkpoint transfer:  77%|███████▋  | 378/491 [02:29<00:48,  2.35it/s]
dSVA checkpoint transfer:  77%|███████▋  | 379/491 [02:30<00:47,  2.35it/s]
dSVA checkpoint transfer:  77%|███████▋  | 380/491 [02:30<00:45,  2.46it/s]
dSVA checkpoint transfer:  78%|███████▊  | 381/491 [02:30<00:45,  2.43it/s]
dSVA checkpoint transfer:  78%|███████▊  | 382/491 [02:31<00:45,  2.42it/s]
dSVA checkpoint transfer:  78%|███████▊  | 383/491 [02:31<00:44,  2.45it/s]
dSVA checkpoint transfer:  78%|███████▊  | 384/491 [02:32<00:40,  2.64it/s]
dSVA checkpoint transfer:  78%|███████▊  | 385/491 [02:32<00:38,  2.73it/s]
dSVA checkpoint transfer:  79%|███████▊  | 386/491 [02:32<00:35,  2.99it/s]
dSVA checkpoint transfer:  79%|███████▉  | 387/491 [02:33<00:41,  2.51it/s]
dSVA checkpoint transfer:  79%|███████▉  | 388/491 [02:33<00:39,  2.58it/s]
dSVA checkpoint transfer:  79%|███████▉  | 389/491 [02:33<00:37,  2.69it/s]
dSVA checkpoint transfer:  79%|███████▉  | 390/491 [02:34<00:35,  2.83it/s]
dSVA checkpoint transfer:  80%|███████▉  | 391/491 [02:34<00:33,  3.00it/s]
dSVA checkpoint transfer:  80%|███████▉  | 392/491 [02:34<00:30,  3.20it/s]
dSVA checkpoint transfer:  80%|████████  | 393/491 [02:35<00:29,  3.28it/s]
dSVA checkpoint transfer:  80%|████████  | 394/491 [02:35<00:28,  3.40it/s]
dSVA checkpoint transfer:  80%|████████  | 395/491 [02:35<00:33,  2.86it/s]
dSVA checkpoint transfer:  81%|████████  | 396/491 [02:36<00:32,  2.97it/s]
dSVA checkpoint transfer:  81%|████████  | 397/491 [02:36<00:30,  3.12it/s]
dSVA checkpoint transfer:  81%|████████  | 398/491 [02:36<00:28,  3.25it/s]
dSVA checkpoint transfer:  81%|████████▏ | 399/491 [02:37<00:28,  3.25it/s]
dSVA checkpoint transfer:  81%|████████▏ | 400/491 [02:37<00:26,  3.41it/s]
dSVA checkpoint transfer:  82%|████████▏ | 401/491 [02:37<00:25,  3.56it/s]
dSVA checkpoint transfer:  82%|████████▏ | 402/491 [02:37<00:23,  3.74it/s]
dSVA checkpoint transfer:  82%|████████▏ | 403/491 [02:38<00:22,  3.85it/s]
dSVA checkpoint transfer:  82%|████████▏ | 404/491 [02:38<00:22,  3.79it/s]
dSVA checkpoint transfer:  82%|████████▏ | 405/491 [02:38<00:22,  3.80it/s]
dSVA checkpoint transfer:  83%|████████▎ | 406/491 [02:38<00:21,  3.87it/s]
dSVA checkpoint transfer:  83%|████████▎ | 407/491 [02:39<00:21,  3.92it/s]
dSVA checkpoint transfer:  83%|████████▎ | 408/491 [02:39<00:21,  3.82it/s]
dSVA checkpoint transfer:  83%|████████▎ | 409/491 [02:39<00:21,  3.77it/s]
dSVA checkpoint transfer:  84%|████████▎ | 410/491 [02:39<00:21,  3.85it/s]
dSVA checkpoint transfer:  84%|████████▎ | 411/491 [02:40<00:20,  3.88it/s]
dSVA checkpoint transfer:  84%|████████▍ | 412/491 [02:40<00:20,  3.85it/s]
dSVA checkpoint transfer:  84%|████████▍ | 413/491 [02:40<00:20,  3.83it/s]
dSVA checkpoint transfer:  84%|████████▍ | 414/491 [02:40<00:20,  3.69it/s]
dSVA checkpoint transfer:  85%|████████▍ | 415/491 [02:41<00:20,  3.76it/s]
dSVA checkpoint transfer:  85%|████████▍ | 416/491 [02:41<00:19,  3.81it/s]
dSVA checkpoint transfer:  85%|████████▍ | 417/491 [02:41<00:19,  3.87it/s]
dSVA checkpoint transfer:  85%|████████▌ | 418/491 [02:41<00:18,  3.96it/s]
dSVA checkpoint transfer:  85%|████████▌ | 419/491 [02:42<00:18,  3.99it/s]
dSVA checkpoint transfer:  86%|████████▌ | 420/491 [02:42<00:17,  4.02it/s]
dSVA checkpoint transfer:  86%|████████▌ | 421/491 [02:42<00:17,  4.00it/s]
dSVA checkpoint transfer:  86%|████████▌ | 422/491 [02:42<00:17,  4.03it/s]
dSVA checkpoint transfer:  86%|████████▌ | 423/491 [02:43<00:16,  4.01it/s]
dSVA checkpoint transfer:  86%|████████▋ | 424/491 [02:43<00:17,  3.85it/s]
dSVA checkpoint transfer:  87%|████████▋ | 425/491 [02:43<00:17,  3.86it/s]
dSVA checkpoint transfer:  87%|████████▋ | 426/491 [02:43<00:16,  3.96it/s]
dSVA checkpoint transfer:  87%|████████▋ | 427/491 [02:44<00:15,  4.01it/s]
dSVA checkpoint transfer:  87%|████████▋ | 428/491 [02:44<00:15,  3.97it/s]

## Aggregate Phase 12 Final Results

In [14]:
run_checked([
    sys.executable,
    'scripts/analyze_phase11_scale_results.py',
    '--scale-root', 'results/phase12_jepa_scale',
    '--output-detail-csv', 'results/phase12_analysis/jepa_scale_detail.csv',
    '--output-aggregate-csv', 'results/phase12_analysis/jepa_scale_aggregate.csv',
])

pd.read_csv(PHASE12_ANALYSIS_DIR / 'jepa_scale_aggregate.csv')

c:\Users\Florent\anaconda3\python.exe scripts/analyze_phase11_scale_results.py --scale-root results/phase12_jepa_scale --output-detail-csv results/phase12_analysis/jepa_scale_detail.csv --output-aggregate-csv results/phase12_analysis/jepa_scale_aggregate.csv
Wrote detail CSV: results\phase12_analysis\jepa_scale_detail.csv
Wrote aggregate CSV: results\phase12_analysis\jepa_scale_aggregate.csv

Log: d:\Florent\Desktop\jepa-transfer-attacks\results\phase12_logs\analyze_phase11_scale_results_11.log

,objectives,run_type,jepa_weight,lr,epochs,train_limit,num_seeds,mean_transfer_success,std_transfer_success,resnet50_mean,resnet50_std,convnext_tiny_mean,convnext_tiny_std,vit_b_16_mean,vit_b_16_std,efficientnet_b0_mean,efficientnet_b0_std,swin_t_mean,swin_t_std
0,dino_mae,control,0.0,0.00005,2,1000,6,0.668460,0.016239,0.708528,0.016590,0.522397,0.013458,0.738188,0.004373,0.948080,0.008155,0.485405,0.010938
1,dino_mae,control,0.0,0.00005,3,1000,3,0.665626,0.001798,0.732886,0.005793,0.547023,0.004127,0.716967,0.003286,NaN,NaN,NaN,NaN
2,dino_mae_jepa,jepa,0.1,0.00005,2,1000,3,0.672113,0.009240,0.715772,0.017998,0.538685,0.007624,0.761882,0.004208,NaN,NaN,NaN,NaN
3,dino_mae_jepa,jepa,0.1,0.00005,3,1000,3,0.674524,0.003878,0.732789,0.000505,0.542564,0.006454,0.748220,0.010083,NaN,NaN,NaN,NaN
4,dino_mae_jepa,jepa,0.2,0.00005,2,1000,6,0.691355,0.015337,0.716842,0.019878,0.545666,0.010468,0.775035,0.005837,0.949265,0.008122,0.528739,0.003127
5,dino_mae_jepa,jepa,0.2,0.00005,3,1000,3,0.681542,0.002566,0.734734,0.003671,0.542370,0.002607,0.767523,0.004586,NaN,NaN,NaN,NaN

## Package CSV Outputs

In [15]:
import tarfile

archive_path = REPO_ROOT / 'results' / 'phase12_csv_artifacts.tar.gz'
paths = list(PHASE11_OUTPUT_DIR.rglob('*.csv'))
paths += list(PHASE11_OUTPUT_DIR.rglob('*.json'))
paths += list(PHASE11_ANALYSIS_DIR.rglob('*.csv'))
paths += list(PHASE12_OUTPUT_DIR.rglob('*.csv'))
paths += list(PHASE12_OUTPUT_DIR.rglob('*.json'))
paths += list(PHASE12_ANALYSIS_DIR.rglob('*.csv'))
for smoke_name in ['phase11_smoke_released_dsva.csv', 'phase12_smoke_released_dsva.csv']:
    smoke_csv = REPO_ROOT / 'results' / smoke_name
    if smoke_csv.exists():
        paths.append(smoke_csv)

with tarfile.open(archive_path, 'w:gz') as tar:
    for path in paths:
        tar.add(path, arcname=path.relative_to(REPO_ROOT))
print('Archive:', archive_path)

Archive: d:\Florent\Desktop\jepa-transfer-attacks\results\phase12_csv_artifacts.tar.gz