# Phase 14: Full ImageNet Validation

This notebook validates the single best Phase 13 setting at larger scale.

Primary claim test:

- Untouched released dSVA checkpoint on the exact same ImageNet validation split.
- Matched DINO+MAE continuation as a diagnostic only.
- DINO+MAE+I-JEPA continuation with `jepa_weight=0.3`, `lr=5e-5`, 2 epochs.

The headline comparison is JEPA continuation vs untouched released dSVA. The matched continuation control is useful for diagnosing whether JEPA is helping beyond a poor continuation recipe, but it is not the primary baseline.

## Setup

In [1]:
import os
import torch
from pathlib import Path

print('CUDA available:', torch.cuda.is_available())
if torch.cuda.is_available():
    print('GPU:', torch.cuda.get_device_name(0))
assert torch.cuda.is_available(), 'A local CUDA GPU is required for this experiment.'

cwd = Path.cwd()
candidates = [cwd, cwd.parent]
REPO_ROOT = next(
    (path for path in candidates if (path / 'scripts' / 'sweep_dsva_jepa_finetune.py').exists()),
    None,
)
assert REPO_ROOT is not None, f'Could not find repo root from {cwd}'
print('Repo root:', REPO_ROOT)

CUDA available: True
GPU: NVIDIA GeForce RTX 2060 SUPER
Repo root: d:\Florent\Desktop\jepa-transfer-attacks

## Configure ImageNet Paths

In [2]:
# Set these environment variables before launching Jupyter, or edit the paths below.
# Expected layout: ImageNet-style class folders. Numeric folders work directly; WNID folders need CLASS_MAP.

def first_existing(*paths):
    for path in paths:
        if path and Path(path).exists():
            return Path(path)
    return None

PHASE14_OUTPUT_DIR = REPO_ROOT / 'results' / 'phase14_imagenet_validation'
PHASE14_ANALYSIS_DIR = REPO_ROOT / 'results' / 'phase14_analysis'
PHASE14_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
PHASE14_ANALYSIS_DIR.mkdir(parents=True, exist_ok=True)

IMAGENET_TRAIN_ROOT = first_existing(
    os.environ.get('IMAGENET_TRAIN_ROOT'),
    REPO_ROOT / 'imagenet_phase14' / 'train',
    REPO_ROOT / 'imagenet' / 'train',
    REPO_ROOT / 'ILSVRC2012' / 'train',
)
IMAGENET_VAL_ROOT = first_existing(
    os.environ.get('IMAGENET_VAL_ROOT'),
    REPO_ROOT / 'imagenet_phase14' / 'val',
    REPO_ROOT / 'imagenet' / 'val',
    REPO_ROOT / 'ILSVRC2012' / 'val',
)
CLASS_MAP = first_existing(
    os.environ.get('IMAGENET_CLASS_MAP'),
    REPO_ROOT / 'imagenet_phase14' / 'imagenet_class_map.json',
    REPO_ROOT / 'configs' / 'imagenet_class_map.json',
)
DSVA_CHECKPOINT = REPO_ROOT / 'external' / 'models' / 'dSVA' / 'model.pth'

assert IMAGENET_TRAIN_ROOT is not None, 'Set IMAGENET_TRAIN_ROOT or edit this cell.'
assert IMAGENET_VAL_ROOT is not None, 'Set IMAGENET_VAL_ROOT or edit this cell.'
assert DSVA_CHECKPOINT.exists(), f'Missing dSVA checkpoint: {DSVA_CHECKPOINT}'

print('ImageNet train root:', IMAGENET_TRAIN_ROOT)
print('ImageNet val root:', IMAGENET_VAL_ROOT)
print('Class map:', CLASS_MAP if CLASS_MAP else 'none yet')
print('dSVA checkpoint:', DSVA_CHECKPOINT)

ImageNet train root: d:\Florent\Desktop\jepa-transfer-attacks\imagenet_phase14\train
ImageNet val root: d:\Florent\Desktop\jepa-transfer-attacks\imagenet_phase14\val
Class map: d:\Florent\Desktop\jepa-transfer-attacks\imagenet_phase14\imagenet_class_map.json
dSVA checkpoint: d:\Florent\Desktop\jepa-transfer-attacks\external\models\dSVA\model.pth

## Auto-Create ImageNet Class Map

In [3]:
import json

if CLASS_MAP is None:
    try:
        from torchvision.datasets import ImageNet
        imagenet_root = IMAGENET_TRAIN_ROOT.parent
        metadata = ImageNet(str(imagenet_root), split='val')
        generated_map = PHASE14_ANALYSIS_DIR / 'imagenet_class_map_from_torchvision.json'
        generated_map.parent.mkdir(parents=True, exist_ok=True)
        generated_map.write_text(json.dumps(metadata.wnid_to_idx, indent=2, sort_keys=True), encoding='utf-8')
        CLASS_MAP = generated_map
        print('Generated class map from torchvision metadata:', CLASS_MAP)
    except Exception as exc:
        print('Could not auto-generate class map from torchvision ImageNet metadata.')
        print('If your ImageNet folders are WNIDs, set IMAGENET_CLASS_MAP to a JSON mapping WNID -> class index.')
        print('If folders are numeric 0..999, no class map is needed.')
        print('Details:', repr(exc))
else:
    print('Using class map:', CLASS_MAP)

Using class map: d:\Florent\Desktop\jepa-transfer-attacks\imagenet_phase14\imagenet_class_map.json

## Experiment Configuration

In [4]:
SEEDS = [0, 1, 2]
TRAIN_LIMIT = 1000
EVAL_LIMIT = 50000
EPSILON = '0.06274509803921569'
LR = '0.00005'
EPOCHS = 2
BEST_CONFIG = '0.3:0.00005'
OUTPUT_MODE = 'scaled-delta'
VICTIMS = ['resnet50', 'convnext_tiny', 'vit_b_16', 'efficientnet_b0', 'swin_t']

TRAIN_PERF_FLAGS = ['--compile', '--compile-mode', 'reduce-overhead']
EVAL_PERF_FLAGS = ['--eval-amp', *TRAIN_PERF_FLAGS]
CLASS_MAP_FLAGS = ['--class-map', str(CLASS_MAP)] if CLASS_MAP else []

print('Output dir:', PHASE14_OUTPUT_DIR)
print('Analysis dir:', PHASE14_ANALYSIS_DIR)
print('Train limit:', TRAIN_LIMIT)
print('Eval limit:', EVAL_LIMIT)
print('Victims:', VICTIMS)
print('Best config:', BEST_CONFIG)
print('Class-map flags:', CLASS_MAP_FLAGS)

Output dir: d:\Florent\Desktop\jepa-transfer-attacks\results\phase14_imagenet_validation
Analysis dir: d:\Florent\Desktop\jepa-transfer-attacks\results\phase14_analysis
Train limit: 1000
Eval limit: 50000
Victims: ['resnet50', 'convnext_tiny', 'vit_b_16', 'efficientnet_b0', 'swin_t']
Best config: 0.3:0.00005
Class-map flags: ['--class-map', 'd:\\Florent\\Desktop\\jepa-transfer-attacks\\imagenet_phase14\\imagenet_class_map.json']

## Helpers

In [5]:
import subprocess, sys
from pathlib import Path

def run_checked(cmd):
    print('\n' + ' '.join(map(str, cmd)), flush=True)
    log_dir = REPO_ROOT / 'results' / 'phase14_logs'
    log_dir.mkdir(parents=True, exist_ok=True)
    log_path = log_dir / (Path(str(cmd[1])).stem + '_' + str(len(list(log_dir.glob('*.log')))) + '.log')
    with log_path.open('w', encoding='utf-8', errors='replace') as handle:
        result = subprocess.run(
            cmd,
            cwd=REPO_ROOT,
            text=True,
            stdout=handle,
            stderr=subprocess.STDOUT,
        )
    text = log_path.read_text(encoding='utf-8', errors='replace')
    print(text[-12000:])
    print('Log:', log_path)
    if result.returncode != 0:
        raise RuntimeError(f"Command failed with exit code {result.returncode}: {' '.join(map(str, cmd))}")
    return result

## Smoke Test

In [6]:
smoke_csv = REPO_ROOT / 'results' / 'phase14_smoke_released_dsva_imagenet.csv'
if smoke_csv.exists():
    print('Skipping existing smoke CSV:', smoke_csv)
else:
    run_checked([
        sys.executable,
        'scripts/run_dsva_checkpoint_attack.py',
        '--data-root', str(IMAGENET_VAL_ROOT),
        '--checkpoint', str(DSVA_CHECKPOINT),
        '--output-mode', 'adv',
        '--limit', '32',
        '--batch-size', '8',
        '--epsilon', EPSILON,
        '--victims', *VICTIMS,
        '--device', 'cuda',
        '--output-csv', str(smoke_csv),
        '--amp',
        *CLASS_MAP_FLAGS,
    ])

c:\Users\Florent\anaconda3\python.exe scripts/run_dsva_checkpoint_attack.py --data-root d:\Florent\Desktop\jepa-transfer-attacks\imagenet_phase14\val --checkpoint d:\Florent\Desktop\jepa-transfer-attacks\external\models\dSVA\model.pth --output-mode adv --limit 32 --batch-size 8 --epsilon 0.06274509803921569 --victims resnet50 convnext_tiny vit_b_16 efficientnet_b0 swin_t --device cuda --output-csv d:\Florent\Desktop\jepa-transfer-attacks\results\phase14_smoke_released_dsva_imagenet.csv --amp --class-map d:\Florent\Desktop\jepa-transfer-attacks\imagenet_phase14\imagenet_class_map.json

dSVA checkpoint transfer:   0%|          | 0/4 [00:00<?, ?it/s]
dSVA checkpoint transfer:  25%|██▌       | 1/4 [00:18<00:54, 18.29s/it]
dSVA checkpoint transfer:  50%|█████     | 2/4 [00:18<00:15,  7.91s/it]
dSVA checkpoint transfer:  75%|███████▌  | 3/4 [00:19<00:04,  4.62s/it]
dSVA checkpoint transfer: 100%|██████████| 4/4 [00:20<00:00,  3.05s/it]
dSVA checkpoint transfer: 100%|██████████| 4/4 [00:20<00:00,  5.07s/it]
| model | n | clean_acc | adv_acc | acc_drop | attack_success_rate |
| --- | ---: | ---: | ---: | ---: | ---: |
| resnet50 | 32 | 96.88% | 50.00% | 46.88% | 48.39% |
| convnext_tiny | 32 | 93.75% | 65.62% | 28.12% | 30.00% |
| vit_b_16 | 32 | 96.88% | 15.62% | 81.25% | 83.87% |
| efficientnet_b0 | 32 | 90.62% | 6.25% | 84.38% | 93.10% |
| swin_t | 32 | 96.88% | 65.62% | 31.25% | 32.26% |

Mean transfer success: 57.52%
Max L_inf delta: 0.062745
Saved metrics to d:\Florent\Desktop\jepa-transfer-attacks\results\phase14_smoke_released_dsva_imagenet.csv

Log: d:\Florent\Desktop\jepa-transfer-attacks\results\phase14_logs\run_dsva_checkpoint_attack_0.log

## Untouched Released dSVA ImageNet Baseline

In [7]:
untouched_csv = PHASE14_ANALYSIS_DIR / 'official_dsva_imagenet_eval.csv'
if untouched_csv.exists():
    print('Skipping existing untouched ImageNet baseline:', untouched_csv)
else:
    run_checked([
        sys.executable,
        'scripts/run_dsva_checkpoint_attack.py',
        '--data-root', str(IMAGENET_VAL_ROOT),
        '--checkpoint', str(DSVA_CHECKPOINT),
        '--output-mode', 'adv',
        '--limit', str(EVAL_LIMIT),
        '--batch-size', '8',
        '--epsilon', EPSILON,
        '--victims', *VICTIMS,
        '--device', 'cuda',
        '--output-csv', str(untouched_csv),
        '--amp',
        *CLASS_MAP_FLAGS,
    ])

c:\Users\Florent\anaconda3\python.exe scripts/run_dsva_checkpoint_attack.py --data-root d:\Florent\Desktop\jepa-transfer-attacks\imagenet_phase14\val --checkpoint d:\Florent\Desktop\jepa-transfer-attacks\external\models\dSVA\model.pth --output-mode adv --limit 50000 --batch-size 8 --epsilon 0.06274509803921569 --victims resnet50 convnext_tiny vit_b_16 efficientnet_b0 swin_t --device cuda --output-csv d:\Florent\Desktop\jepa-transfer-attacks\results\phase14_analysis\official_dsva_imagenet_eval.csv --amp --class-map d:\Florent\Desktop\jepa-transfer-attacks\imagenet_phase14\imagenet_class_map.json
ansfer:  98%|█████████▊| 6109/6250 [1:01:40<00:57,  2.47it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6110/6250 [1:01:40<00:55,  2.53it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6111/6250 [1:01:41<00:55,  2.51it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6112/6250 [1:01:41<00:54,  2.53it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6113/6250 [1:01:42<00:54,  2.54it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6114/6250 [1:01:42<00:52,  2.59it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6115/6250 [1:01:42<00:52,  2.56it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6116/6250 [1:01:43<00:55,  2.41it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6117/6250 [1:01:43<00:53,  2.50it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6118/6250 [1:01:44<00:51,  2.56it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6119/6250 [1:01:44<00:51,  2.56it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6120/6250 [1:01:44<00:49,  2.61it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6121/6250 [1:01:45<00:55,  2.34it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6122/6250 [1:01:45<00:56,  2.28it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6123/6250 [1:01:46<00:53,  2.39it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6124/6250 [1:01:46<00:52,  2.40it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6125/6250 [1:01:47<00:50,  2.47it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6126/6250 [1:01:47<00:52,  2.38it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6127/6250 [1:01:47<00:52,  2.34it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6128/6250 [1:01:48<00:50,  2.43it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6129/6250 [1:01:48<00:50,  2.38it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6130/6250 [1:01:49<00:47,  2.50it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6131/6250 [1:01:49<00:47,  2.51it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6132/6250 [1:01:49<00:45,  2.61it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6133/6250 [1:01:50<00:44,  2.60it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6134/6250 [1:01:50<00:43,  2.65it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6135/6250 [1:01:50<00:43,  2.65it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6136/6250 [1:01:51<00:42,  2.67it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6137/6250 [1:01:51<00:43,  2.57it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6138/6250 [1:01:52<00:44,  2.51it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6139/6250 [1:01:52<00:46,  2.41it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6140/6250 [1:01:52<00:43,  2.51it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6141/6250 [1:01:53<00:41,  2.61it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6142/6250 [1:01:53<00:41,  2.59it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6143/6250 [1:01:54<00:42,  2.50it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6144/6250 [1:01:54<00:42,  2.51it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6145/6250 [1:01:54<00:40,  2.60it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6146/6250 [1:01:55<00:41,  2.53it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6147/6250 [1:01:55<00:40,  2.57it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6148/6250 [1:01:56<00:39,  2.60it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6149/6250 [1:01:56<00:38,  2.65it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6150/6250 [1:01:56<00:40,  2.47it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6151/6250 [1:01:57<00:39,  2.53it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6152/6250 [1:01:57<00:39,  2.51it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6153/6250 [1:01:58<00:37,  2.61it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6154/6250 [1:01:58<00:36,  2.62it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6155/6250 [1:01:58<00:37,  2.55it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6156/6250 [1:01:59<00:36,  2.54it/s]
dSVA checkpoint transfer:  99%|█████████▊| 6157/6250 [1:01:59<00:37,  2.50it/s]
dSVA checkpoint transfer:  99%|█████████▊| 6158/6250 [1:02:00<00:36,  2.50it/s]
dSVA checkpoint transfer:  99%|█████████▊| 6159/6250 [1:02:00<00:37,  2.41it/s]
dSVA checkpoint transfer:  99%|█████████▊| 6160/6250 [1:02:00<00:39,  2.27it/s]
dSVA checkpoint transfer:  99%|█████████▊| 6161/6250 [1:02:01<00:38,  2.29it/s]
dSVA checkpoint transfer:  99%|█████████▊| 6162/6250 [1:02:01<00:37,  2.34it/s]
dSVA checkpoint transfer:  99%|█████████▊| 6163/6250 [1:02:02<00:40,  2.15it/s]
dSVA checkpoint transfer:  99%|█████████▊| 6164/6250 [1:02:02<00:37,  2.31it/s]
dSVA checkpoint transfer:  99%|█████████▊| 6165/6250 [1:02:03<00:38,  2.19it/s]
dSVA checkpoint transfer:  99%|█████████▊| 6166/6250 [1:02:03<00:37,  2.26it/s]
dSVA checkpoint transfer:  99%|█████████▊| 6167/6250 [1:02:04<00:35,  2.36it/s]
dSVA checkpoint transfer:  99%|█████████▊| 6168/6250 [1:02:04<00:33,  2.45it/s]
dSVA checkpoint transfer:  99%|█████████▊| 6169/6250 [1:02:04<00:33,  2.40it/s]
dSVA checkpoint transfer:  99%|█████████▊| 6170/6250 [1:02:05<00:32,  2.49it/s]
dSVA checkpoint transfer:  99%|█████████▊| 6171/6250 [1:02:05<00:31,  2.51it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6172/6250 [1:02:05<00:30,  2.57it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6173/6250 [1:02:06<00:31,  2.44it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6174/6250 [1:02:06<00:30,  2.53it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6175/6250 [1:02:07<00:28,  2.59it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6176/6250 [1:02:07<00:29,  2.52it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6177/6250 [1:02:07<00:27,  2.61it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6178/6250 [1:02:08<00:27,  2.67it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6179/6250 [1:02:08<00:27,  2.58it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6180/6250 [1:02:09<00:26,  2.63it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6181/6250 [1:02:09<00:26,  2.64it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6182/6250 [1:02:09<00:27,  2.48it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6183/6250 [1:02:10<00:26,  2.51it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6184/6250 [1:02:10<00:25,  2.55it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6185/6250 [1:02:11<00:26,  2.49it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6186/6250 [1:02:11<00:25,  2.53it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6187/6250 [1:02:11<00:25,  2.45it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6188/6250 [1:02:12<00:25,  2.43it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6189/6250 [1:02:12<00:24,  2.53it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6190/6250 [1:02:13<00:23,  2.60it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6191/6250 [1:02:13<00:22,  2.60it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6192/6250 [1:02:13<00:21,  2.65it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6193/6250 [1:02:14<00:21,  2.67it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6194/6250 [1:02:14<00:22,  2.50it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6195/6250 [1:02:14<00:21,  2.56it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6196/6250 [1:02:15<00:20,  2.59it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6197/6250 [1:02:15<00:20,  2.58it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6198/6250 [1:02:16<00:20,  2.56it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6199/6250 [1:02:16<00:19,  2.59it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6200/6250 [1:02:16<00:19,  2.62it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6201/6250 [1:02:17<00:20,  2.41it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6202/6250 [1:02:17<00:19,  2.49it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6203/6250 [1:02:18<00:18,  2.60it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6204/6250 [1:02:18<00:18,  2.54it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6205/6250 [1:02:18<00:17,  2.57it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6206/6250 [1:02:19<00:16,  2.65it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6207/6250 [1:02:19<00:16,  2.57it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6208/6250 [1:02:20<00:17,  2.36it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6209/6250 [1:02:20<00:17,  2.30it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6210/6250 [1:02:21<00:17,  2.25it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6211/6250 [1:02:21<00:17,  2.20it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6212/6250 [1:02:21<00:16,  2.28it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6213/6250 [1:02:22<00:16,  2.22it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6214/6250 [1:02:22<00:15,  2.26it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6215/6250 [1:02:23<00:14,  2.37it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6216/6250 [1:02:23<00:14,  2.39it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6217/6250 [1:02:24<00:14,  2.28it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6218/6250 [1:02:24<00:13,  2.39it/s]
dSVA checkpoint transfer: 100%|█████████▉| 6219/6250 [1:02:24<00:12,  2.41it/s]
dSVA checkpoint transfer: 100%|█████████▉| 6220/6250 [1:02:25<00:11,  2.52it/s]
dSVA checkpoint transfer: 100%|█████████▉| 6221/6250 [1:02:25<00:11,  2.55it/s]
dSVA checkpoint transfer: 100%|█████████▉| 6222/6250 [1:02:26<00:10,  2.56it/s]
dSVA checkpoint transfer: 100%|█████████▉| 6223/6250 [1:02:26<00:10,  2.55it/s]
dSVA checkpoint transfer: 100%|█████████▉| 6224/6250 [1:02:26<00:10,  2.52it/s]
dSVA checkpoint transfer: 100%|█████████▉| 6225/6250 [1:02:27<00:09,  2.61it/s]
dSVA checkpoint transfer: 100%|█████████▉| 6226/6250 [1:02:27<00:09,  2.57it/s]
dSVA checkpoint transfer: 100%|█████████▉| 6227/6250 [1:02:28<00:09,  2.48it/s]
dSVA checkpoint transfer: 100%|█████████▉| 6228/6250 [1:02:28<00:08,  2.51it/s]
dSVA checkpoint transfer: 100%|█████████▉| 6229/6250 [1:02:28<00:08,  2.42it/s]
dSVA checkpoint transfer: 100%|█████████▉| 6230/6250 [1:02:29<00:08,  2.42it/s]
dSVA checkpoint transfer: 100%|█████████▉| 6231/6250 [1:02:29<00:08,  2.33it/s]
dSVA checkpoint transfer: 100%|█████████▉| 6232/6250 [1:02:30<00:08,  2.24it/s]
dSVA checkpoint transfer: 100%|█████████▉| 6233/6250 [1:02:30<00:07,  2.31it/s]
dSVA checkpoint transfer: 100%|█████████▉| 6234/6250 [1:02:31<00:07,  2.22it/s]
dSVA checkpoint transfer: 100%|█████████▉| 6235/6250 [1:02:31<00:06,  2.20it/s]
dSVA checkpoint transfer: 100%|█████████▉| 6236/6250 [1:02:32<00:06,  2.25it/s]
dSVA checkpoint transfer: 100%|█████████▉| 6237/6250 [1:02:32<00:06,  2.11it/s]
dSVA checkpoint transfer: 100%|█████████▉| 6238/6250 [1:02:33<00:05,  2.10it/s]
dSVA checkpoint transfer: 100%|█████████▉| 6239/6250 [1:02:33<00:04,  2.21it/s]
dSVA checkpoint transfer: 100%|█████████▉| 6240/6250 [1:02:33<00:04,  2.33it/s]
dSVA checkpoint transfer: 100%|█████████▉| 6241/6250 [1:02:34<00:03,  2.46it/s]
dSVA checkpoint transfer: 100%|█████████▉| 6242/6250 [1:02:34<00:03,  2.47it/s]
dSVA checkpoint transfer: 100%|█████████▉| 6243/6250 [1:02:34<00:02,  2.57it/s]
dSVA checkpoint transfer: 100%|█████████▉| 6244/6250 [1:02:35<00:02,  2.51it/s]
dSVA checkpoint transfer: 100%|█████████▉| 6245/6250 [1:02:35<00:02,  2.46it/s]
dSVA checkpoint transfer: 100%|█████████▉| 6246/6250 [1:02:36<00:01,  2.47it/s]
dSVA checkpoint transfer: 100%|█████████▉| 6247/6250 [1:02:36<00:01,  2.40it/s]
dSVA checkpoint transfer: 100%|█████████▉| 6248/6250 [1:02:36<00:00,  2.43it/s]
dSVA checkpoint transfer: 100%|█████████▉| 6249/6250 [1:02:37<00:00,  2.46it/s]
dSVA checkpoint transfer: 100%|██████████| 6250/6250 [1:02:37<00:00,  2.39it/s]
dSVA checkpoint transfer: 100%|██████████| 6250/6250 [1:02:37<00:00,  1.66it/s]
| model | n | clean_acc | adv_acc | acc_drop | attack_success_rate |
| --- | ---: | ---: | ---: | ---: | ---: |
| resnet50 | 50000 | 80.15% | 27.83% | 52.32% | 66.69% |
| convnext_tiny | 50000 | 81.86% | 39.90% | 41.96% | 52.85% |
| vit_b_16 | 50000 | 80.89% | 16.34% | 64.55% | 80.46% |
| efficientnet_b0 | 50000 | 77.69% | 4.90% | 72.79% | 94.05% |
| swin_t | 50000 | 81.33% | 41.51% | 39.82% | 50.55% |

Mean transfer success: 68.92%
Max L_inf delta: 0.062745
Saved metrics to d:\Florent\Desktop\jepa-transfer-attacks\results\phase14_analysis\official_dsva_imagenet_eval.csv

Log: d:\Florent\Desktop\jepa-transfer-attacks\results\phase14_logs\run_dsva_checkpoint_attack_1.log

In [8]:
import pandas as pd

untouched = pd.read_csv(untouched_csv)
untouched_mean = untouched['attack_success_rate'].mean()
print('Untouched ImageNet mean:', f'{100 * untouched_mean:.2f}%')
untouched

Untouched ImageNet mean: 68.92%

             model      n  clean_acc  adv_acc  acc_drop  attack_success_rate
0         resnet50  50000    0.80148  0.27826   0.52322             0.666891
1    convnext_tiny  50000    0.81860  0.39900   0.41960             0.528537
2         vit_b_16  50000    0.80892  0.16340   0.64552             0.804604
3  efficientnet_b0  50000    0.77688  0.04896   0.72792             0.940480
4           swin_t  50000    0.81332  0.41514   0.39818             0.505533

## Best JEPA Continuation vs Matched Control

In [9]:
for seed in SEEDS:
    seed_dir = PHASE14_OUTPUT_DIR / f'seed_{seed}'
    seed_dir.mkdir(parents=True, exist_ok=True)
    cmd = [
        sys.executable,
        'scripts/sweep_dsva_jepa_finetune.py',
        '--train-root', str(IMAGENET_TRAIN_ROOT),
        '--val-root', str(IMAGENET_VAL_ROOT),
        '--init-checkpoint', str(DSVA_CHECKPOINT),
        '--output-dir', str(seed_dir),
        '--run-prefix', f'phase14_seed{seed}_imagenet_jw0p3_ep{EPOCHS}',
        '--configs', BEST_CONFIG,
        '--limit', str(TRAIN_LIMIT),
        '--eval-limit', str(EVAL_LIMIT),
        '--epochs', str(EPOCHS),
        '--batch-size', '1',
        '--eval-batch-size', '8',
        '--grad-accum-steps', '8',
        '--epsilon', EPSILON,
        '--output-mode', OUTPUT_MODE,
        '--victims', *VICTIMS,
        '--device', 'cuda',
        '--seed', str(seed),
        '--normalize-loss-weights',
        '--skip-existing',
        *EVAL_PERF_FLAGS,
        *CLASS_MAP_FLAGS,
    ]
    run_checked(cmd)

c:\Users\Florent\anaconda3\python.exe scripts/sweep_dsva_jepa_finetune.py --train-root d:\Florent\Desktop\jepa-transfer-attacks\imagenet_phase14\train --val-root d:\Florent\Desktop\jepa-transfer-attacks\imagenet_phase14\val --init-checkpoint d:\Florent\Desktop\jepa-transfer-attacks\external\models\dSVA\model.pth --output-dir d:\Florent\Desktop\jepa-transfer-attacks\results\phase14_imagenet_validation\seed_0 --run-prefix phase14_seed0_imagenet_jw0p3_ep2 --configs 0.3:0.00005 --limit 1000 --eval-limit 50000 --epochs 2 --batch-size 1 --eval-batch-size 8 --grad-accum-steps 8 --epsilon 0.06274509803921569 --output-mode scaled-delta --victims resnet50 convnext_tiny vit_b_16 efficientnet_b0 swin_t --device cuda --seed 0 --normalize-loss-weights --skip-existing --eval-amp --compile --compile-mode reduce-overhead --class-map d:\Florent\Desktop\jepa-transfer-attacks\imagenet_phase14\imagenet_class_map.json
A checkpoint transfer:  98%|█████████▊| 6110/6250 [40:34<00:45,  3.04it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6111/6250 [40:34<00:45,  3.05it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6112/6250 [40:34<00:45,  3.02it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6113/6250 [40:35<00:46,  2.97it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6114/6250 [40:35<00:44,  3.07it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6115/6250 [40:35<00:46,  2.91it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6116/6250 [40:36<00:48,  2.76it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6117/6250 [40:36<00:50,  2.62it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6118/6250 [40:36<00:47,  2.79it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6119/6250 [40:37<00:46,  2.82it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6120/6250 [40:37<00:45,  2.86it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6121/6250 [40:38<00:49,  2.59it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6122/6250 [40:38<00:53,  2.40it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6123/6250 [40:38<00:52,  2.44it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6124/6250 [40:39<00:52,  2.39it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6125/6250 [40:39<00:49,  2.55it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6126/6250 [40:40<00:48,  2.57it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6127/6250 [40:40<00:47,  2.59it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6128/6250 [40:40<00:45,  2.67it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6129/6250 [40:41<00:44,  2.71it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6130/6250 [40:41<00:43,  2.76it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6131/6250 [40:41<00:44,  2.68it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6132/6250 [40:42<00:41,  2.84it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6133/6250 [40:42<00:39,  2.95it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6134/6250 [40:42<00:40,  2.89it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6135/6250 [40:43<00:39,  2.92it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6136/6250 [40:43<00:38,  2.94it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6137/6250 [40:43<00:38,  2.91it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6138/6250 [40:44<00:38,  2.93it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6139/6250 [40:44<00:38,  2.87it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6140/6250 [40:44<00:37,  2.96it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6141/6250 [40:45<00:35,  3.03it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6142/6250 [40:45<00:37,  2.85it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6143/6250 [40:45<00:36,  2.97it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6144/6250 [40:46<00:35,  2.99it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6145/6250 [40:46<00:34,  3.07it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6146/6250 [40:46<00:36,  2.88it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6147/6250 [40:47<00:36,  2.85it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6148/6250 [40:47<00:37,  2.74it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6149/6250 [40:48<00:34,  2.89it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6150/6250 [40:48<00:35,  2.83it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6151/6250 [40:48<00:33,  2.93it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6152/6250 [40:49<00:35,  2.79it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6153/6250 [40:49<00:38,  2.51it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6154/6250 [40:49<00:36,  2.63it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6155/6250 [40:50<00:37,  2.57it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6156/6250 [40:50<00:35,  2.66it/s]
dSVA checkpoint transfer:  99%|█████████▊| 6157/6250 [40:51<00:34,  2.67it/s]
dSVA checkpoint transfer:  99%|█████████▊| 6158/6250 [40:51<00:35,  2.61it/s]
dSVA checkpoint transfer:  99%|█████████▊| 6159/6250 [40:51<00:33,  2.73it/s]
dSVA checkpoint transfer:  99%|█████████▊| 6160/6250 [40:52<00:35,  2.56it/s]
dSVA checkpoint transfer:  99%|█████████▊| 6161/6250 [40:52<00:34,  2.57it/s]
dSVA checkpoint transfer:  99%|█████████▊| 6162/6250 [40:53<00:35,  2.50it/s]
dSVA checkpoint transfer:  99%|█████████▊| 6163/6250 [40:53<00:34,  2.55it/s]
dSVA checkpoint transfer:  99%|█████████▊| 6164/6250 [40:53<00:33,  2.56it/s]
dSVA checkpoint transfer:  99%|█████████▊| 6165/6250 [40:54<00:33,  2.55it/s]
dSVA checkpoint transfer:  99%|█████████▊| 6166/6250 [40:54<00:31,  2.67it/s]
dSVA checkpoint transfer:  99%|█████████▊| 6167/6250 [40:54<00:30,  2.70it/s]
dSVA checkpoint transfer:  99%|█████████▊| 6168/6250 [40:55<00:29,  2.76it/s]
dSVA checkpoint transfer:  99%|█████████▊| 6169/6250 [40:55<00:30,  2.66it/s]
dSVA checkpoint transfer:  99%|█████████▊| 6170/6250 [40:56<00:29,  2.69it/s]
dSVA checkpoint transfer:  99%|█████████▊| 6171/6250 [40:56<00:31,  2.52it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6172/6250 [40:56<00:30,  2.59it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6173/6250 [40:57<00:29,  2.65it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6174/6250 [40:57<00:27,  2.77it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6175/6250 [40:57<00:26,  2.81it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6176/6250 [40:58<00:25,  2.90it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6177/6250 [40:58<00:24,  2.99it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6178/6250 [40:58<00:23,  3.02it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6179/6250 [40:59<00:25,  2.83it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6180/6250 [40:59<00:24,  2.83it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6181/6250 [40:59<00:24,  2.87it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6182/6250 [41:00<00:23,  2.95it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6183/6250 [41:00<00:23,  2.82it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6184/6250 [41:00<00:23,  2.84it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6185/6250 [41:01<00:24,  2.66it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6186/6250 [41:01<00:23,  2.76it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6187/6250 [41:02<00:22,  2.83it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6188/6250 [41:02<00:21,  2.82it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6189/6250 [41:02<00:21,  2.85it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6190/6250 [41:03<00:20,  2.92it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6191/6250 [41:03<00:22,  2.64it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6192/6250 [41:03<00:21,  2.71it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6193/6250 [41:04<00:20,  2.83it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6194/6250 [41:04<00:20,  2.70it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6195/6250 [41:04<00:19,  2.76it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6196/6250 [41:05<00:18,  2.86it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6197/6250 [41:05<00:18,  2.94it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6198/6250 [41:05<00:18,  2.80it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6199/6250 [41:06<00:18,  2.76it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6200/6250 [41:06<00:17,  2.89it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6201/6250 [41:07<00:16,  2.89it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6202/6250 [41:07<00:17,  2.73it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6203/6250 [41:07<00:16,  2.82it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6204/6250 [41:08<00:16,  2.86it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6205/6250 [41:08<00:15,  2.94it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6206/6250 [41:08<00:14,  2.93it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6207/6250 [41:09<00:14,  2.95it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6208/6250 [41:09<00:14,  2.97it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6209/6250 [41:09<00:15,  2.73it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6210/6250 [41:10<00:14,  2.69it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6211/6250 [41:10<00:14,  2.64it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6212/6250 [41:10<00:14,  2.69it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6213/6250 [41:11<00:15,  2.38it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6214/6250 [41:11<00:14,  2.40it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6215/6250 [41:12<00:13,  2.53it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6216/6250 [41:12<00:13,  2.61it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6217/6250 [41:12<00:11,  2.77it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6218/6250 [41:13<00:11,  2.75it/s]
dSVA checkpoint transfer: 100%|█████████▉| 6219/6250 [41:13<00:10,  2.82it/s]
dSVA checkpoint transfer: 100%|█████████▉| 6220/6250 [41:13<00:10,  2.87it/s]
dSVA checkpoint transfer: 100%|█████████▉| 6221/6250 [41:14<00:09,  2.91it/s]
dSVA checkpoint transfer: 100%|█████████▉| 6222/6250 [41:14<00:09,  2.95it/s]
dSVA checkpoint transfer: 100%|█████████▉| 6223/6250 [41:15<00:09,  2.81it/s]
dSVA checkpoint transfer: 100%|█████████▉| 6224/6250 [41:15<00:09,  2.83it/s]
dSVA checkpoint transfer: 100%|█████████▉| 6225/6250 [41:15<00:08,  2.89it/s]
dSVA checkpoint transfer: 100%|█████████▉| 6226/6250 [41:16<00:08,  2.88it/s]
dSVA checkpoint transfer: 100%|█████████▉| 6227/6250 [41:16<00:08,  2.84it/s]
dSVA checkpoint transfer: 100%|█████████▉| 6228/6250 [41:16<00:08,  2.64it/s]
dSVA checkpoint transfer: 100%|█████████▉| 6229/6250 [41:17<00:08,  2.60it/s]
dSVA checkpoint transfer: 100%|█████████▉| 6230/6250 [41:17<00:07,  2.71it/s]
dSVA checkpoint transfer: 100%|█████████▉| 6231/6250 [41:18<00:07,  2.63it/s]
dSVA checkpoint transfer: 100%|█████████▉| 6232/6250 [41:18<00:06,  2.65it/s]
dSVA checkpoint transfer: 100%|█████████▉| 6233/6250 [41:18<00:06,  2.76it/s]
dSVA checkpoint transfer: 100%|█████████▉| 6234/6250 [41:19<00:05,  2.77it/s]
dSVA checkpoint transfer: 100%|█████████▉| 6235/6250 [41:19<00:05,  2.66it/s]
dSVA checkpoint transfer: 100%|█████████▉| 6236/6250 [41:19<00:05,  2.65it/s]
dSVA checkpoint transfer: 100%|█████████▉| 6237/6250 [41:20<00:05,  2.47it/s]
dSVA checkpoint transfer: 100%|█████████▉| 6238/6250 [41:20<00:04,  2.43it/s]
dSVA checkpoint transfer: 100%|█████████▉| 6239/6250 [41:21<00:04,  2.55it/s]
dSVA checkpoint transfer: 100%|█████████▉| 6240/6250 [41:21<00:03,  2.67it/s]
dSVA checkpoint transfer: 100%|█████████▉| 6241/6250 [41:21<00:03,  2.76it/s]
dSVA checkpoint transfer: 100%|█████████▉| 6242/6250 [41:22<00:02,  2.82it/s]
dSVA checkpoint transfer: 100%|█████████▉| 6243/6250 [41:22<00:02,  2.87it/s]
dSVA checkpoint transfer: 100%|█████████▉| 6244/6250 [41:22<00:02,  2.80it/s]
dSVA checkpoint transfer: 100%|█████████▉| 6245/6250 [41:23<00:01,  2.70it/s]
dSVA checkpoint transfer: 100%|█████████▉| 6246/6250 [41:23<00:01,  2.77it/s]
dSVA checkpoint transfer: 100%|█████████▉| 6247/6250 [41:23<00:01,  2.82it/s]
dSVA checkpoint transfer: 100%|█████████▉| 6248/6250 [41:24<00:00,  2.96it/s]
dSVA checkpoint transfer: 100%|█████████▉| 6249/6250 [41:24<00:00,  2.88it/s]
dSVA checkpoint transfer: 100%|██████████| 6250/6250 [41:24<00:00,  2.90it/s]
dSVA checkpoint transfer: 100%|██████████| 6250/6250 [41:24<00:00,  2.52it/s]
| model | n | clean_acc | adv_acc | acc_drop | attack_success_rate |
| --- | ---: | ---: | ---: | ---: | ---: |
| resnet50 | 50000 | 80.14% | 26.36% | 53.79% | 68.46% |
| convnext_tiny | 50000 | 81.86% | 41.10% | 40.76% | 51.40% |
| vit_b_16 | 50000 | 80.89% | 14.68% | 66.22% | 82.45% |
| efficientnet_b0 | 50000 | 77.70% | 3.62% | 74.08% | 95.60% |
| swin_t | 50000 | 81.33% | 38.64% | 42.69% | 53.97% |

Mean transfer success: 70.38%
Max L_inf delta: 0.062744
Saved metrics to d:\Florent\Desktop\jepa-transfer-attacks\results\phase14_imagenet_validation\seed_0\phase14_seed0_imagenet_jw0p3_ep2_jw0p3_lr0p00005_eval.csv
Updated sweep summary: d:\Florent\Desktop\jepa-transfer-attacks\results\phase14_imagenet_validation\seed_0\phase14_seed0_imagenet_jw0p3_ep2_summary.csv

Saved sweep summary to d:\Florent\Desktop\jepa-transfer-attacks\results\phase14_imagenet_validation\seed_0\phase14_seed0_imagenet_jw0p3_ep2_summary.csv

Log: d:\Florent\Desktop\jepa-transfer-attacks\results\phase14_logs\sweep_dsva_jepa_finetune_2.log

c:\Users\Florent\anaconda3\python.exe scripts/sweep_dsva_jepa_finetune.py --train-root d:\Florent\Desktop\jepa-transfer-attacks\imagenet_phase14\train --val-root d:\Florent\Desktop\jepa-transfer-attacks\imagenet_phase14\val --init-checkpoint d:\Florent\Desktop\jepa-transfer-attacks\external\models\dSVA\model.pth --output-dir d:\Florent\Desktop\jepa-transfer-attacks\results\phase14_imagenet_validation\seed_1 --run-prefix phase14_seed1_imagenet_jw0p3_ep2 --configs 0.3:0.00005 --limit 1000 --eval-limit 50000 --epochs 2 --batch-size 1 --eval-batch-size 8 --grad-accum-steps 8 --epsilon 0.06274509803921569 --output-mode scaled-delta --victims resnet50 convnext_tiny vit_b_16 efficientnet_b0 swin_t --device cuda --seed 1 --normalize-loss-weights --skip-existing --eval-amp --compile --compile-mode reduce-overhead --class-map d:\Florent\Desktop\jepa-transfer-attacks\imagenet_phase14\imagenet_class_map.json
/6250 [1:04:28<00:56,  2.42it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6114/6250 [1:04:29<00:55,  2.45it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6115/6250 [1:04:29<00:53,  2.53it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6116/6250 [1:04:29<00:54,  2.47it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6117/6250 [1:04:30<00:53,  2.48it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6118/6250 [1:04:30<00:52,  2.54it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6119/6250 [1:04:31<00:51,  2.54it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6120/6250 [1:04:31<00:50,  2.58it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6121/6250 [1:04:32<00:57,  2.25it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6122/6250 [1:04:32<00:58,  2.19it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6123/6250 [1:04:35<02:25,  1.15s/it]
dSVA checkpoint transfer:  98%|█████████▊| 6124/6250 [1:04:37<03:16,  1.56s/it]
dSVA checkpoint transfer:  98%|█████████▊| 6125/6250 [1:04:40<03:50,  1.85s/it]
dSVA checkpoint transfer:  98%|█████████▊| 6126/6250 [1:04:43<04:20,  2.10s/it]
dSVA checkpoint transfer:  98%|█████████▊| 6127/6250 [1:04:46<04:53,  2.39s/it]
dSVA checkpoint transfer:  98%|█████████▊| 6128/6250 [1:04:49<05:12,  2.56s/it]
dSVA checkpoint transfer:  98%|█████████▊| 6129/6250 [1:04:52<05:26,  2.70s/it]
dSVA checkpoint transfer:  98%|█████████▊| 6130/6250 [1:04:54<05:19,  2.66s/it]
dSVA checkpoint transfer:  98%|█████████▊| 6131/6250 [1:04:57<05:07,  2.58s/it]
dSVA checkpoint transfer:  98%|█████████▊| 6132/6250 [1:04:59<04:59,  2.54s/it]
dSVA checkpoint transfer:  98%|█████████▊| 6133/6250 [1:05:01<04:52,  2.50s/it]
dSVA checkpoint transfer:  98%|█████████▊| 6134/6250 [1:05:02<03:57,  2.04s/it]
dSVA checkpoint transfer:  98%|█████████▊| 6135/6250 [1:05:04<03:42,  1.93s/it]
dSVA checkpoint transfer:  98%|█████████▊| 6136/6250 [1:05:04<02:47,  1.47s/it]
dSVA checkpoint transfer:  98%|█████████▊| 6137/6250 [1:05:05<02:08,  1.14s/it]
dSVA checkpoint transfer:  98%|█████████▊| 6138/6250 [1:05:05<01:41,  1.10it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6139/6250 [1:05:06<01:26,  1.28it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6140/6250 [1:05:06<01:11,  1.53it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6141/6250 [1:05:06<01:01,  1.78it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6142/6250 [1:05:07<00:57,  1.88it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6143/6250 [1:05:07<00:51,  2.07it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6144/6250 [1:05:08<00:48,  2.20it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6145/6250 [1:05:08<00:44,  2.36it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6146/6250 [1:05:08<00:43,  2.40it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6147/6250 [1:05:09<00:42,  2.44it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6148/6250 [1:05:09<00:39,  2.55it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6149/6250 [1:05:09<00:38,  2.61it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6150/6250 [1:05:10<00:39,  2.54it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6151/6250 [1:05:10<00:37,  2.62it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6152/6250 [1:05:11<00:36,  2.67it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6153/6250 [1:05:11<00:38,  2.51it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6154/6250 [1:05:11<00:38,  2.49it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6155/6250 [1:05:12<00:38,  2.46it/s]
dSVA checkpoint transfer:  98%|█████████▊| 6156/6250 [1:05:12<00:36,  2.54it/s]
dSVA checkpoint transfer:  99%|█████████▊| 6157/6250 [1:05:13<00:36,  2.57it/s]
dSVA checkpoint transfer:  99%|█████████▊| 6158/6250 [1:05:13<00:36,  2.49it/s]
dSVA checkpoint transfer:  99%|█████████▊| 6159/6250 [1:05:13<00:35,  2.58it/s]
dSVA checkpoint transfer:  99%|█████████▊| 6160/6250 [1:05:14<00:37,  2.40it/s]
dSVA checkpoint transfer:  99%|█████████▊| 6161/6250 [1:05:16<01:28,  1.01it/s]
dSVA checkpoint transfer:  99%|█████████▊| 6162/6250 [1:05:18<01:46,  1.21s/it]
dSVA checkpoint transfer:  99%|█████████▊| 6163/6250 [1:05:19<01:32,  1.06s/it]
dSVA checkpoint transfer:  99%|█████████▊| 6164/6250 [1:05:22<02:24,  1.68s/it]
dSVA checkpoint transfer:  99%|█████████▊| 6165/6250 [1:05:22<01:53,  1.33s/it]
dSVA checkpoint transfer:  99%|█████████▊| 6166/6250 [1:05:23<01:27,  1.04s/it]
dSVA checkpoint transfer:  99%|█████████▊| 6167/6250 [1:05:23<01:11,  1.16it/s]
dSVA checkpoint transfer:  99%|█████████▊| 6168/6250 [1:05:23<00:58,  1.39it/s]
dSVA checkpoint transfer:  99%|█████████▊| 6169/6250 [1:05:24<00:50,  1.60it/s]
dSVA checkpoint transfer:  99%|█████████▊| 6170/6250 [1:05:24<00:43,  1.82it/s]
dSVA checkpoint transfer:  99%|█████████▊| 6171/6250 [1:05:25<00:40,  1.95it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6172/6250 [1:05:25<00:38,  2.02it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6173/6250 [1:05:25<00:35,  2.17it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6174/6250 [1:05:26<00:34,  2.18it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6175/6250 [1:05:26<00:32,  2.31it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6176/6250 [1:05:27<00:32,  2.29it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6177/6250 [1:05:27<00:29,  2.45it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6178/6250 [1:05:27<00:28,  2.54it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6179/6250 [1:05:28<00:27,  2.57it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6180/6250 [1:05:28<00:26,  2.64it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6181/6250 [1:05:29<00:27,  2.49it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6182/6250 [1:05:29<00:26,  2.61it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6183/6250 [1:05:29<00:25,  2.68it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6184/6250 [1:05:30<00:25,  2.61it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6185/6250 [1:05:30<00:25,  2.60it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6186/6250 [1:05:31<00:24,  2.58it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6187/6250 [1:05:31<00:24,  2.59it/s]
dSVA checkpoint transfer:  99%|█████████▉| 6188/6250 [1:05:31<00:23,  2.60it/s]

## Aggregate and Compare

In [10]:
run_checked([
    sys.executable,
    'scripts/analyze_phase11_scale_results.py',
    '--scale-root', 'results/phase14_imagenet_validation',
    '--output-detail-csv', 'results/phase14_analysis/imagenet_detail.csv',
    '--output-aggregate-csv', 'results/phase14_analysis/imagenet_aggregate.csv',
])

aggregate = pd.read_csv(PHASE14_ANALYSIS_DIR / 'imagenet_aggregate.csv')
aggregate

c:\Users\Florent\anaconda3\python.exe scripts/analyze_phase11_scale_results.py --scale-root results/phase14_imagenet_validation --output-detail-csv results/phase14_analysis/imagenet_detail.csv --output-aggregate-csv results/phase14_analysis/imagenet_aggregate.csv
Wrote detail CSV: results\phase14_analysis\imagenet_detail.csv
Wrote aggregate CSV: results\phase14_analysis\imagenet_aggregate.csv

Log: d:\Florent\Desktop\jepa-transfer-attacks\results\phase14_logs\analyze_phase11_scale_results_5.log

,objectives,run_type,jepa_weight,lr,epochs,train_limit,num_seeds,mean_transfer_success,std_transfer_success,resnet50_mean,resnet50_std,convnext_tiny_mean,convnext_tiny_std,vit_b_16_mean,vit_b_16_std,efficientnet_b0_mean,efficientnet_b0_std,swin_t_mean,swin_t_std
0,dino_mae,control,0.0,0.00005,2,1000,3,0.707670,0.012077,0.679377,0.026652,0.521895,0.018520,0.839663,0.000858,0.950318,0.005055,0.547099,0.011110
1,dino_mae_jepa,jepa,0.3,0.00005,2,1000,3,0.699803,0.010318,0.671791,0.025799,0.504263,0.017288,0.831899,0.006750,0.952790,0.005798,0.538271,0.007425

In [11]:
rows = aggregate.copy()
rows['mean_transfer_success'] = rows['mean_transfer_success'].astype(float)
control = rows[rows['run_type'] == 'control'].iloc[0]
jepa = rows[rows['run_type'] == 'jepa'].iloc[0].copy()

summary = {
    'untouched_mean': untouched_mean,
    'control_mean': float(control['mean_transfer_success']),
    'jepa_mean': float(jepa['mean_transfer_success']),
    'gain_vs_untouched': float(jepa['mean_transfer_success']) - untouched_mean,
    'gain_vs_control': float(jepa['mean_transfer_success']) - float(control['mean_transfer_success']),
}
print({key: f'{100 * value:.2f}%' if 'mean' in key else f'{100 * value:+.2f} pts' for key, value in summary.items()})

victim_baseline = untouched.set_index('model')['attack_success_rate'].to_dict()
for victim in VICTIMS:
    column = f'{victim}_mean'
    if column in jepa and victim in victim_baseline:
        print(victim, f"{100 * (float(jepa[column]) - victim_baseline[victim]):+.2f} pts vs untouched")

{'untouched_mean': '68.92%', 'control_mean': '70.77%', 'jepa_mean': '69.98%', 'gain_vs_untouched': '+1.06 pts', 'gain_vs_control': '-0.79 pts'}
resnet50 +0.49 pts vs untouched
convnext_tiny -2.43 pts vs untouched
vit_b_16 +2.73 pts vs untouched
efficientnet_b0 +1.23 pts vs untouched
swin_t +3.27 pts vs untouched

## Decision Read

In [12]:
gain = summary['gain_vs_untouched']
if gain >= 0.01:
    print('Decision: full ImageNet validation supports a workshop/short-paper claim.')
elif gain > 0:
    print('Decision: positive but modest; report carefully or add per-image complementarity before claiming scale.')
else:
    print('Decision: do not claim ImageNet-scale improvement; keep the result as an Imagenette/domain-adaptation finding.')

Decision: full ImageNet validation supports a workshop/short-paper claim.

## Package CSV Outputs

In [13]:
import tarfile

archive_path = REPO_ROOT / 'results' / 'phase14_csv_artifacts.tar.gz'
paths = list(PHASE14_OUTPUT_DIR.rglob('*.csv'))
paths += list(PHASE14_ANALYSIS_DIR.rglob('*.csv'))
if smoke_csv.exists():
    paths.append(smoke_csv)

with tarfile.open(archive_path, 'w:gz') as tar:
    for path in paths:
        tar.add(path, arcname=path.relative_to(REPO_ROOT))
print('Archive:', archive_path)

Archive: d:\Florent\Desktop\jepa-transfer-attacks\results\phase14_csv_artifacts.tar.gz